module/plugins/hoster/NitroflareCom.py

Right now captcha decoding is failing. I think that is due to the reason that site is not allowing free downloads. or maybe pyload is not able to decode google's new captcha. I cannot confirm as I have not been though the process of downloading even once. Thus, my knowledge of their process is limited.
Fixes #876

plugin for nitroflare.com

---

module/plugins/accounts/SmoozedCom.py
module/plugins/hooks/SmoozedCom.py
module/plugins/hoster/SmoozedCom.py

Scripts needed for multihoster smoozed.com.
We are a quiet new service and are giving away free 14 days accounts in the time of our beta phase.
Please send me a private message containing your email address or send an email to github@smoozed.com.
Your account will be created in a short time.

Added multihoster smoozed.com

---

module/plugins/hoster/BasePlugin.py

[BasePlugin] Fix another typo

---

module/plugins/accounts/RehostTo.py
module/plugins/hooks/RehostTo.py
module/plugins/hoster/RehostTo.py

[RehostTo] Fixed

---

module/plugins/internal/CaptchaService.py

Fix for https://github.com/pyload/pyload/issues/976

[CaptchaService.py] Added support for ReCaptchaV2

---

module/plugins/crypter/FilecryptCc.py

Fix for https://github.com/pyload/pyload/issues/976

[FilecryptCc.py] Added support for ReCaptchaV2

---

module/plugins/accounts/RapidgatorNet.py

Rapidgator premium account unable to download problem
https://github.com/pyload/pyload/issues/1086

[RapidgatorNet] Bug fix for premium account

---

module/plugins/accounts/ShareonlineBiz.py

ShareOnline: Handle PrePaid accounts as if they were Premium Accounts

---

module/plugins/hoster/FreeWayMe.py

This update allows 4 additional attempts if download fails.
If there are small parts to improve (style, ...), please feel free to do it yourself. I'm busy next days. Thanks for merging!

Host FreeWayMe: Improve error handling, try five times

---

module/plugins/internal/CaptchaService.py

Some small changes to make ReCaptchaV2 work again.

[CaptchaService.py] Fix ReCaptchaV2

---

module/plugins/hoster/XdadevelopersCom.py

Just a small plugin to download stuff from XDA's DevDB

[New Hoster] xdadevelopers.com

---

module/plugins/hoster/AndroidfilehostCom.py

Another plugin for downloading android-stuff.

[New Hoster] androidfilehost.com

---

module/plugins/internal/UnZip.py

Just testet your latest commit (strip() Uploaded Info) with my zip file and discovered some Typos in the UnZip.py
Test on Windows. Working.

[UnZip] Fixed Typo

---

module/plugins/hoster/GoogledriveCom.py

A simple plugin to download public shared files from drive.google.com

[New Hoster] drive.google.com

---

module/plugins/hooks/ExtractArchive.py
module/plugins/internal/UnRar.py

Some Changes that fix little Problems.
Some other still remain:
- after Extraction the remainig parts are logged as skipped -> ugly
- sevenzip is absolutely damaged, cant get it working
- can't find a list of supported File formats for Unrar, so that this can be defined precisely 
- also it seems not to extract when package finished (although option Wait for all downloads to be finished: is false)

Addressed some Extractor Issues

---

module/plugins/hooks/ExtractArchive.py

I'm producing wrong working code as well ;)

[ExtractArchive] Fixed: Recursive Extraction

---

module/plugins/hoster/BasketbuildCom.py

I want to download my android stuff via pyLoad ;)

[New Hoster] basketbuild.com

---

module/plugins/hooks/RestartSlow.py

https://github.com/pyload/pyload/issues/1143

[RestartSlow] Fixed AttributeError

---

module/plugins/hoster/DevhostSt.py

They have changed their website, the plugin was not working anymore.

[Hoster] Update DevhostSt.py

---

module/plugins/internal/CaptchaService.py

Some additional requests to make it work again.

[CaptchaService.py] Updated Solvemedia

---

module/plugins/hooks/ExtractArchive.py
module/plugins/internal/Extractor.py
module/plugins/internal/SevenZip.py
module/plugins/internal/UnRar.py
module/plugins/internal/UnZip.py

hope thats ok, I'm not familiar with threaded programming. 
If there is an easier way to get the active thread or the connection for displaying the file in Overview please change it.

[ExtractArchive] Some more changes

---

module/plugins/hoster/MystoreTo.py

As requested in https://github.com/pyload/pyload/issues/1169

[New Hoster] mystore.to

---

module/plugins/hooks/FreeWayMe.py

We need this since some hosts are limited to specific users

[Hook] Free-way.me: Use login data while getting host list

---

module/plugins/hooks/JustPremium.py

Because I didn't find an option to block some hoster that are marked as premium in multihosters, i added the possibility to block them in this hook. 
Some multihoster have problems with some hoster, but list them nevertheless as supported by their service. 
Also when specifying "whitelisted" free hoster in excluded, they are now handled as prefered by dropping other free hoster when excluded is given.

[JustPremium] Include hoster to remove

---

module/plugins/hoster/ZippyshareCom.py

* remove non word characters from the id part in the js variable name.
* change the RE that fetches getElementById so that it works for any character in the id name.

[ZippyShare] Bug #1238 correction

---

module/plugins/hoster/ZippyshareCom.py

Handle funky introspection like :
```javascript
test = {
test: function(x, y) {
document.getElementById(x).href = y;
}
test.test('dlbutton', "http:\\ZippyshareIsFullOfTrickster.com");
```

[zippyshare] bug correction #1246

---

module/plugins/hoster/NitroflareCom.py

They changed their Address back to http://..... Tested

[NitroflareCom] Switch back to http

---

module/plugins/hooks/AntiVirus.py

With the Comment within the config array, not all config items are shown in webUI

[AntiVirus] Typo & Remove Comment within Array

---

module/plugins/hooks/ExtractArchive.py
module/plugins/internal/Extractor.py
module/plugins/internal/UnRar.py

https://github.com/pyload/pyload/issues/1271

[ExtractArchive] extract archive even if first part is not in package

---

module/plugins/internal/UnRar.py

now that checking if file is multipart only apply on finding files to delete no further check is required. 
(this fixes including again rev and damaged files)

[ExtractArchive] Bugfix

---

module/plugins/hooks/ExtractArchive.py

fixed "permanent" issue

---

module/plugins/hoster/RgHostNet.py

add rghost.ru and fix link_free_patern

rghost issue #1289

---

module/plugins/hoster/IfolderRu.py

add metalare.org and fixed for new layout of page

ifolder issue #1291

---

module/plugins/hoster/OneFichierCom.py

Quick fix: Onefichier Premium incorrect filename

Fix issue  #1042

---

module/plugins/hoster/OneFichierCom.py

Error was : 
WARNING   Download failed: filename | global name 'link' is not defined

Fix code problem for premium download with OneFichier

---

module/plugins/hoster/Keep2ShareCc.py

Problem is not fixed. With this change we are able to load captcha, but after that I have Parse error: No file downloaded | Plugin may be out of date. I can see dwnload page in temp folder

Some issue in keep2share.cc #1236

---

module/plugins/hoster/YadiSk

[hoster request]yadi.sk #1292

---

module/plugins/hoster/RemixshareCom.py

Please Merge my changes on Remixshare Plugin

Fixed RemixshareCom

---

module/plugins/hoster/Solidfiles.py

I added a new Hoster named Solidfiles.com

Added new Hoster Solidfiles.com

---

module/plugins/hoster/LolabitsEs.py

As requested in https://github.com/pyload/pyload/issues/1343

[New Hoster] lolabits.es

---

module/plugins/hoster/HostujeNet.py

[New Hoster] HostujeNet

---

module/plugins/crypter/FilecryptCc.py

Fix https://github.com/pyload/pyload/issues/1364

[FilecryptCc.py] Fix circle captcha

---

module/plugins/crypter/FilecryptCc.py

Fix https://github.com/pyload/pyload/issues/1364 again ;)

[FilecryptCc.py] Avoid hardcoded urls

---

module/plugins/hoster/UploadedTo.py

[UploadedTo] detect maintenance

---

module/plugins/internal/SimpleHoster.py

[SimpleHoster] fix 'Content-Disposition' filename sometime missing first and last chars

---

module/plugins/hoster/UpleaCom.py

[UpleaCom]  fix file size calculation and Set DISPOSITION to False (temp)

---

module/plugins/hoster/SizedriveCom.py

Forum ref: http://forum.pyload.org/viewtopic.php?f=13&t=4201

[New Hoster] sizedrive.com

---

module/plugins/hooks/AntiVirus.py
module/plugins/hooks/ExtractArchive.py

Hi,
This PR makes ExtractArchive and AntiVirus inform the user when send2trash library is not installed.

[ExtractArchive] [AntiVirus] report missing send2trash

---

module/plugins/hooks/ClickAndLoad.py

[ClickAndLoad] update

---

module/plugins/accounts/SmoozedCom.py

When the account is not premium, check if there is trial time left.

Fixed #1399

---

module/plugins/internal/CaptchaService.py

Fix https://github.com/pyload/pyload/issues/1423

[CaptchaService.py] Update ReCaptchaV1

---

module/plugins/hoster/NitroflareCom.py

Key is necessary, because cannot be obtained automatically (also the variable is referred some lines further in the code)

[NitroFlare] Re-Added RECAPTCHA_KEY

---

module/plugins/hoster/GoogledriveCom.py

Support links like 
`
https://drive.google.com/uc?export=download&id=<dl_id_here> 
`
See forum: http://forum.pyload.org/viewtopic.php?f=13&t=4203

[GoogledriveCom] Make it more flexible

---

module/plugins/hoster/DlFreeFr.py

@vuolter 
Added missing download call which was removed in a previous code cleanup.

Added missing download call

---

module/plugins/accounts/HighWayMe.py
module/plugins/hooks/HighWayMe.py
module/plugins/hoster/HighWayMe.py

In module/plugins/hoster/HighWayMe.py someone need to change line 27. I have added an Comment, but I don't now how to solve it.

Added High-Way.Me

---

module/plugins/accounts/RealdebridCom.py

Fix this: DEBUG	RealdebridCom: Account Info: {'error': "local variable 'xml' referenced before assignment"}

RealDebridCom.py: RealdebridCom: Account Info: {'error': "local variable 'xml' referenced before assignment"}

---

module/plugins/crypter/FilecryptCc.py

Fix https://github.com/pyload/pyload/issues/1614

[FilecryptCc.py] Fix https://github.com/pyload/pyload/issues/1614

---

module/plugins/accounts/ShareonlineBiz.py
module/plugins/hoster/ShareonlineBiz.py

Replaced HTTP with HTTPS in order not to reveal user credentials.

Fix for issue #1654

---

module/plugins/internal/Plugin.py
module/plugins/internal/SimpleHoster.py
module/plugins/internal/XFSAccount.py

fix #1684 #1681 #1680 #1677 #1674

Object has no attribute 'COOKIES'

---

module/plugins/accounts/XFileSharingPro.py

fix XFileSharingPro.py cannot be updated

---

module/plugins/accounts/UploadedTo.py

https://github.com/pyload/pyload/issues/1694

...has no attribute "COOKIES"

---

module/plugins/internal/Account.py

[Account] fix relogin not working

---

module/plugins/hoster/OneFichierCom.py

Updated regexp, website now displays "File Name" instead of "FileName".

File name not found on OneFichier

---

module/plugins/accounts/RapidgatorNet.py

Small fix, presumably for an API endpoint URL change on Rapidgator's side.

[accounts/RapidgatorNet] Fixes #1698

---

module/plugins/hoster/YoutubeCom.py

[YoutubeCom] fix #1744

---

module/plugins/hooks/ExternalScripts.py

fix ExternalScripts not working

---

module/plugins/accounts/OneFichierCom.py

OneFichier valid pattern has changed

OneFichierCom premium detection fixed

---

module/plugins/crypter/MultiUpOrg.py
module/plugins/internal/SimpleCrypter.py

[SimpleCrypter] [MultiUpOrg] fix #1765

---

module/plugins/crypter/LinkCryptWs.py
module/plugins/internal/Captcha.py

This fixes the 'bool' object has no attribute 'decrypt' Error. As mentioned there might be another problem with the cookie handling

[LinkCryptWs] partly fixes #1756

---

module/plugins/crypter/SexuriaCom.py

Fixes some errors appeared with recent code changes (function name refactoring, plugins.internal)

[crypter/SexuriaCom] Fix for recent code change

---

module/plugins/hooks/TransmissionRPC.py

Send torrent and magnet URLs to Transmission Bittorent daemon so you can use pyload's `ClickAndLoad` to send links to transmission.

[New Hook] TransmissionRPC

---

module/plugins/hoster/OneFichierCom.py

[OneFichierCom] fix #1768

---

module/plugins/internal/Hoster.py

[Hoster] fix pyfile.name not updated if disposition

---

module/plugins/crypter/LinkCryptWs.py

i think it's a question of design, if the plugin downloads the captcha image or the decrypt method does it itself. But this hopefully fixes the issue.

fixes #1756 completly

---

module/plugins/internal/Plugin.py
module/plugins/internal/SimpleHoster.py

Remove accents from file name #1817

---

module/plugins/accounts/UptoboxCom.py

The UptoboxCom account plugin is not working anymore.
I made changes and it's now working very well.

[UptoboxCom] account update

---

module/plugins/hoster/PremiumizeMe.py

[PremiumizeMe] update

---

module/plugins/internal/Plugin.py

[Plugin.py] fix #1787 and #1749

---

module/plugins/internal/SimpleHoster.py

[SimpleHoster] update

---

module/plugins/crypter/LinkCryptWs.py

Reload/double-load Page and Smoozed is away

Fix for SMOOZED

---

module/plugins/internal/Hoster.py

Version up

---

module/plugins/hoster/ZippyshareCom.py

[ZippyshareCom] fix #1861

---

module/plugins/crypter/FilecryptCc.py

fix #1805, #1781
must commit #1882 to be able to use.
Tested successfully with internal & solvemedia captcha.
Could not get a circlecaptcha to test but probably works
Recaptcha mostly don't work if any

[FilecryptCc] update

---

module/plugins/internal/Base.py

Fix for the issue with http://url.tld/http://url.tld/XXX

Double URL Fix

---

module/plugins/internal/Base.py

[Base] update

---

module/plugins/hoster/EuroshareEu.py

Euroshare.eu is ok

---

module/plugins/hoster/EuroshareEu.py

Fix NAME_PATTERN and SIZE_PATTERN

Fix EuroshareEu

---

module/plugins/hooks/UpdateManager.py

fix #2045
Current version of `UpdateManager` requests wrong URL and so, gives `404` for account(s) and hook(s) plugins but does not report about 404 correctly (because of `is` instead of `==`)
This may explain all the weired stuff lately.. 
You'll have to manually update your `UpdateManager` to get full updates back.

[UpdateManager] fix #2045

---

module/plugins/hooks/TransmissionRPC.py

Hi
ffd38f027ed103f7b39ec78c6af0d182774950a4 breaks `TransmissionRPC`:
[TransmissionRPC.py#L59](https://github.com/pyload/pyload/blob/ffd38f027ed103f7b39ec78c6af0d182774950a4/module/plugins/hooks/TransmissionRPC.py#L59) never gets excecuted if `BadHeader(409)`

[TransmissionRPC] update

---

module/plugins/internal/utils.py

This fixes my problem mit filecrypt.cc crypter
dont know if it would fix any other hoster or crypter issues

Fix for https://github.com/pyload/pyload/issues/2025

---

module/plugins/hooks/PushBullet.py

PushBullet (it's free) hook based on AndroidPhoneNotify.py

PushBullet hook

---

module/plugins/hooks/PushOver.py

PushOver hook based on AndroidPhoneNotify.py

PushOver hook

---

module/plugins/internal/UnZip.py

Further to #2063, this updates  `UnZip` also

[UnZip] update

---

module/plugins/internal/Base.py

[Base] update 

---

module/plugins/internal/XFSHoster.py

[XFSHoster] fix #2086

---

module/plugins/hooks/PushOver.py

msg can't be None or empty for PushOver.

PushOver fix

---

module/plugins/hoster/XFileSharing.py

[XFileSharing] update

---

module/plugins/hoster/UpleaCom.py

[UpleaCom] fix #2170

---

module/plugins/hoster/Keep2ShareCc.py

keep2share requires parsing a "uniqueId" and post it. I tested it with a handful of links.

fixed Keep2Share

---

module/plugins/hoster/ZippyshareCom.py

It uses some JS to emulate a document - so it'll be simpler to add any JS function in case Zippyshare's devs decide to add deeper introspection.
It has worked for several months on my side - it's quite the same code actually.

simpler version

---

module/plugins/crypter/LinkCryptWs.py

Add one missing `self` and fix download link parsing. While on it, also replace
oudated `%` string formatting operator with recommended `.format()` method. See [PEP 3101](https://www.python.org/dev/peps/pep-3101/).

[LinkCryptWs] Small fixes

---

module/plugins/captcha/UlozTo.py
module/plugins/hoster/UlozTo.py

I would like to add this feature to the base ulozto source code. More info could be found at https://github.com/izderadicka/adecaptcha and I hope @izderadicka would not mind this PR.

[UlozTo] Added support for audio Captcha recognition

---

module/plugins/hoster/UlozTo.py

I accidentally left  `self.captcha.decrypt(data[image])` line after if statement

[UlozTo] fix captcha

---

module/plugins/hoster/UlozTo.py

ulozto changed downloading form. This patch should fix it.

[UlozTo] Fix new version

---

module/plugins/crypter/ImgurCom.py

Imgur lazy-loads the first 10 images only.
Added code to evaluate Imgur's JSON data in order to find and add the remaining images.

ImgurCom.py Galleries downloaded incompletely

---

module/plugins/accounts/CzshareCom.py
module/plugins/hoster/CzshareCom.py

Add https support.
Fix bad credit left pattern

Fix SdilejCZ/CzshareCom

---

module/plugins/accounts/UlozTo.py
module/plugins/hoster/UlozTo.py

Fix UlozTo

---

module/plugins/crypter/ShareLinksBiz.py

[ShareLinksBiz] Speed up link parsing by cascading through all available container types.
~~[Captcha.py] Change string formatting to `.format()` here as well. Also fixes an `TypeError`
occuring on line 106.~~

Few plugin changes

---

module/plugins/hoster/StreamCz.py

Stream plugin doesn't work...
(Thx Gamma C0de...)

Fix StreamCz

---

module/plugins/hooks/ExtractArchive.py
module/plugins/internal/Extractor.py
module/plugins/internal/UnRar.py
module/plugins/internal/UnTar.py
module/plugins/internal/UnZip.py

ExtractArchive Fix/#2168

---

module/plugins/crypter/HoerbuchIn.py

Hoerbuch.in moved to hoerbuch.us.

Fixed hoerbuchIn plugin

---

module/plugins/hoster/FastshareCz.py

[FastshareCz] free pattern update

---

module/plugins/hoster/StreamCz.py

Fix StreamCz plugin

---

module/plugins/accounts/UlozTo.py
module/plugins/hoster/UlozTo.py

Fix UlozTo hoster

---

module/plugins/accounts/UlozTo.py

another changes in uloz.to website

[UlozTo] Fix account

---

module/plugins/hoster/UlozTo.py

Fix UlozTo.py

---

module/plugins/hoster/OnlineTvRecorder.py

[OnlineTvRecorder] additional download server 93.115.84.162

---

module/plugins/accounts/UploadedTo.py

Display correct valid until date even if expiration is less than an hour away.

[UploadedTo] Display correct valid until date even if expiration is near

---

module/plugins/hoster/DlFreeFr.py

The long URL (like http://dl.free.fr/getfile.pl?file=/xxxxx) were ok
but the shorts (like http://dl.free.fr/xxxxx) were not

[DlFreeFr] Fix short url handling

---

module/plugins/accounts/FastshareCz.py

Fix FastshareCz acc

---

README.md

Chat Links

---

module/plugins/crypter/RelinkUs.py

relink.us no longer worked. 
The password script moved to password2.php and to get to the real site 2 redirects have to be followed

Crypter Relink.us Update

---

src/pyload/core/init.py

`Process.start` expects a Process instance as parameter, to correctly start it

[master] Correctly start Core process

---

src/pyload/core/datatype/debug.py
src/pyload/core/datatype/init.py

Related to https://github.com/pyload/requests/pull/3, this datatype is no longer used in `core`.

[master] Remove Connection datatype

---

module/plugins/hoster/RapidgatorNet.py

> **NOTE:**
[Rapidgator Plugin] add https on regex patern
> **NOTE:**
> If this is a **plugin** request, remember to increase the value of the
> `__version__` attribute inside the files you're submitting.
1. **Related pull requests**: _OPTIONAL_
2. **Related issues**: _OPTIONAL_
_OPTIONAL_
_OPTIONAL_

[Rapidgator Plugin] add https on regex patern

---

.gitignore

> **NOTE:**
Update .gitignore for PyCharm and add *.po translation files
> **NOTE:**
> If this is a **plugin** request, remember to increase the value of the
> `__version__` attribute inside the files you're submitting.
1. **Related pull requests**: _OPTIONAL_
2. **Related issues**: _OPTIONAL_
_OPTIONAL_
_OPTIONAL_

[master] Update .gitignore

---

pyload/api/base.py

correctly extend Api so that methods have access to object variables.
otherwise extension methods do not have access to self.pyload (Core) etc.

correctly extend Api

---

pyload/core/database/backend.py
pyload/utils/fs.py

temporary fix for octal values. resolves: https://github.com/pyload/pyload/pull/2978
until we have a better solution implmented, see: https://github.com/pyload/pyload/pull/2978#issuecomment-335802804

fix octal values

---

module/plugins/hoster/FileSharkPl.py

FileShark.pl chaged from http to https and also download form has changed

FileShark.pl: add https, adaptation to the new form

---

module/plugins/accounts/FastshareCz.py
module/plugins/hoster/FastshareCz.py

> **NOTE:**
Fix https link.
_OPTIONAL_
_OPTIONAL_

Fix fastshare

---

pyload/utils/debug.py
pyload/utils/fs.py

utils/debug.py fix broken method headers
utils/fs.py remove developer output statements

fixing utils

---

pyload/requests/base/request.py
pyload/requests/cookie.py

requests/base/request.py make _abort protected and instantiate CONTEXT_CLASS
requests/cookie.py temp fix not sure what the idea was when it was implemented

make abort protected and instantiate context

---

pyload/config/parser.py
pyload/core/database/backend.py
pyload/core/datatype/file.py
pyload/core/datatype/package.py
pyload/core/manager/event.py
pyload/core/manager/file.py
pyload/core/network/hoster.py
pyload/core/network/loader.py
pyload/core/thread/download.py
pyload/core/thread/plugin.py
requirements/install.txt

fixes listed below:
parser.py set store default value to False to only save config when explicitely requested. Otherwise the config is written as many times as parameters are read from the config.ini
database/backend.py temp fix to have pyload and not get an exception while handling exceptions in process_job
datatype/file.py initial plugin after creating file and fix problem with id -> fid
datatype/package.py add Package to __slots__
manager/event.py while debugging log events
manager/file.py correct documentation
network/hoster.py small fixes
network/loader.py change read string instead of bytes from file
thread/download.py return event instead of boolean
thread/plugin.py write string instead of bytes
requirements/install.txt add requirement for enum34 for python 2.7

many minor fixes

---

module/plugins/hooks/DiscordNotifier.py

I've added a new notifier in the fashion of Pushbullet just for Discord.
It works via a Discord webhook to send the message.
I have all my notifications in a Discord channel so now it's all in one place. :)

Added discord notifier plugin.

---

module/plugins/hoster/OnlineTvRecorder.py

onlinetvrecorder v0.04: Additional download url

---

module/plugins/hoster/OnlineTvRecorder.py

onlinetvrecorder v0.05 support https

---

module/plugins/hoster/XHamsterCom.py

> **NOTE:**
- [ x] Plugin bugfix/enhancement
Update outdated xhamster plugin
The plugin was not working anymore
NA

Upate outdated XHamsterCom plugin

---

module/plugins/hoster/XVideosCom.py

> **NOTE:**
- [ x] Plugin bugfix/enhancement
Update the outdated xvideos.com plugin
The plugin was not working anymore
NA

Update outdated XvideosCom plugin

---

module/plugins/accounts/RealdebridCom.py
module/plugins/hoster/RealdebridCom.py

1. Verify free-account correctly.
2. Able to login with username and password (instead of given api-token as password).

Realdebrid

---

module/plugins/hoster/DailymotionCom.py

1. Fix get-stream-pattern for HTTPS. Check getting valid streams before download.
2. Able to identify URLs with domain "dai.ly".

Dailymotion pattern fixing

---

CLA.md

> **NOTE:**
Fixes #3059.
#3059

Fixed links in CLA.md

---

module/plugins/hoster/UlozTo.py

file URL
> **NOTE:**
UlozTo changed the way how file URL is obtained. New way uses XMLHttpRequest and URL is present in json that is send as a response to provided captcha value.
_OPTIONAL_
_OPTIONAL_

Update UlozTo plugin. Add support for XMLHttpRequest

---

module/plugins/hooks/XMPP.py

Hello,
Change pyxmp in sleekxmpp.
Which allowed:
- fix:
- disconnection after a inactivity moment
- reconnection after loss of connection
- respect the SRV record dns

[XMPP] mod: pyxmpp by sleekxmpp

---

module/plugins/hooks/XMPP.py

Hello,
Minor change:
- add shortuct packinfo
- delete obsolete function

[XMPP] Module/plugins/hooks/xmpp.py

---

module/plugins/accounts/PorntrexCom.py
module/plugins/hoster/PorntrexCom.py

Add PorntrexCom Hoster and Account

Add PorntrexCom Hoster and Account

---

module/plugins/internal/SimpleCrypter.py
module/plugins/internal/SimpleHoster.py
module/plugins/internal/misc.py

this may stabilize `search_pattern` slightly, plus it makes `SimpleHoster` and `SimpleCrypter` more readable. I didn't do any testing yet though. Also see https://github.com/pyload/pyload/issues/3374#issuecomment-491906260 in issue #3374

move search pattern checks into search_pattern

---

src/pyload/__init__.py

this only fixes parts of it, are you taking PR's?  for me you still need to add https://github.com/ahupp/python-magic and libmagic as well as some of the imports, unless this breaks other things?

fix issubclass and resource_filename

---

module/plugins/hoster/DdlTo.py

fix #3477 
added filename replacements

fixed ddl.to filename

---

module/plugins/accounts/UlozTo.py
module/plugins/hoster/UlozTo.py

Maybe free DL not working? I will check and fix soon as possible..

Fix uloz.to premium

---

module/plugins/hoster/DdlTo.py

[pyload/pyload] Can't add my premium ddl.to account. (#3582)

[plugins] ddl.to new API-Address

---

src/pyload/plugins/downloaders/FilejokerNet.py

Update INFO_PATTERN with actual pattern and so change version

Update FilejokerNet.py INFO_PATTERN

---

pyLoadCore.py

On windows, accidentally starting a second instance of pyload with same the configdir wipes the pidfile.
Code adopted from psutil (psutil_pid_is_running + psutil_check_phandle), some parts omitted:
https://github.com/giampaolo/psutil/blob/994c429c010049a6a0556ce3b0d1af1f86f27867/psutil/arch/windows/process_utils.c

Check for running process on windows

---

module/plugins/hoster/NippyshareCom.py

Added Hoster Nippyshare
Nippyshare was missing and not working with XFilesharing Plugin
Example link: `https://nippyshare.com/v/675edc`

New hoster Nippyshare

---

module/plugins/hoster/CosmoboxOrg.py

Added hoster cosmobox.org as requested in #3774
Sample link:  https://cosmobox.org/if35ulgnw9wp

[New Hoster] Cosmobox Org

---

module/plugins/crypter/HoerbuchIn.py

Hoerbuch.in moved to "https", this PR changes all relevant links
Sample link: https://www.hoerbuch.us/protection/folder_148937.html
(I will also provide a patch for the development branch)
The links are no longer detected as belonging to hoerbuch.in, but as base plugins.

[Plugin] Updated Crypter Plugin HoerbuchIn

---

.travis.yml

This PR should fix the macOS job on our Travis CI test pipeline.

Fix macOS test on Travis CI

---

src/pyload/webui/app/templates/base.html
src/pyload/webui/app/templates/js/base.js
src/pyload/webui/app/themes/modern/static/css/settings.css
src/pyload/webui/app/themes/modern/templates/base.html
src/pyload/webui/app/themes/modern/templates/logs.html
src/pyload/webui/app/themes/pyplex/static/css/settings.css

The commit regarding the url_for refactor creates some issues in the modern theme:
log page was no longer working, due to missing )
Renaming of general_form_content to core_form_content was mssing in .css file
Renaming von aktiv to active was missing in modern theme base.html
This PR fixes these issues

[Main] Fixes from url_for refactor

---

module/plugins/crypter/ChipDe.py

Same as for development branch: #3835

[Plugin] Fix Crypter Chip.de

---

src/pyload/plugins/extractors/UnZip.py

Better implementation with bumped version

UnZip Remove files based on exclusion list (#3872)

---

module/plugins/hoster/UploadshipCom.py

New Hoster Uploadship.com added
Sample url: https://www.uploadship.com/8751a59d05c8b10e

[New Hoster] Uploadship Com

---

module/plugins/hoster/FileuploadCom.py

New Hoster Fileupload.com
Sample link: https://www.file-upload.com/7od2xagu3vi3
This hoster is different from fileupload.net which is already supported

[New Hoster] Fileupload Com

---

module/plugins/hoster/UseruploadNet.py

Added new Hoster Userupload.Net
Sample link:
https://userupload.net/t88dwntmmy1i

[New Hoster] Userupload Net

---

src/pyload/plugins/downloaders/ZDF.py

I updated the plugin to work with the current version of webpage zdf.de
#3810
The first link in the issue isn't available anymore, the 2nd one is working. I checked with several links they all worked

[Main] Update of Plugin ZDF.de

---

src/pyload/plugins/downloaders/UploadgigCom.py

The json response from uploadgig has changed. The changed file reflects these changes
Download with uploadgig isn't possible. Error message: Illegal response from the server
```
[2021-08-07 13:34:59]  DEBUG               pyload  DOWNLOADER UploadgigCom[103]: Plugin version: 0.06
[2021-08-07 13:34:59]  DEBUG               pyload  DOWNLOADER UploadgigCom[103]: Plugin status: testing
[2021-08-07 13:34:59]  WARNING             pyload  DOWNLOADER UploadgigCom[103]: Plugin ist eventuell instabil
[2021-08-07 13:34:59]  INFO                pyload  DOWNLOADER UploadgigCom[103]: Suche Link info...
[2021-08-07 13:35:00]  DEBUG               pyload  DOWNLOADER UploadgigCom[103]: Link info: {'name': 'sa-verschwun.rar', 'hash': {}, 'pattern': {'N': 'sa-verschwun.rar', 'S': '1.1', 'U': 'MB'}, 'size': …
```

[Main] Fix downloads with Uploadgig

---

Dockerfile

This is to make the Dockerfile build the image. These are minimal changes to pass the build.
The current Dockerfile is flawed and it would not build the Docker image.

A few modifications to fix the Docker image

---

Dockerfile

This is to make the Dockerfile build the image. These are minimal changes to pass the build.
The current Dockerfile is flawed and it would not build the Docker image.
Ported over from https://github.com/pyload/pyload/pull/3999

 A few modifications to fix the Docker image

---

src/pyload/plugins/downloaders/TurbobitNet.py

- add another base url
handle "turb.pw" with turbobitNet plugin

[TurbobitNet] fixed new base url

---

src/pyload/plugins/downloaders/FileStoreTo.py

A Download will retried if they fail with HTTP 503. This happed on this hoster if you download to many file at the same time. 
Yes, see #4186

Add Bad Header (HTTP 503) Retry Feature

---

src/pyload/plugins/downloaders/KrakenfilesCom.py

Update the filehash element regex to be less brittle if new attrs are added to the HTML element.
`HOSTER KrakenfilesCom[1]: Free download failed | hash pattern not found`
Fixes #4283

Update file hash regex to fix KrakenfilesCom plugin (Fixes #4283)

---

src/pyload/plugins/downloaders/SoundcloudCom.py

Fix SoundCloud 401 Unauthorized
401 Unauthorized when downloading from SoundCloud
https://github.com/pyload/pyload/issues/4299

Fix SoundCloud #4299

---

src/pyload/plugins/accounts/FiregetCom.py

adds fireget.com account plugin

[FiregetCom] adds fireget.com account plugin

---

src/pyload/plugins/decrypters/MegaCoNzFolder.py
tests/test_mega_nz_folder.py

Support filtering a list of mega.nz files down to a single sub folder.

[MegaCoNzFolder]  #4349

---

src/pyload/plugins/addons/ExtractArchive.py

In file: ExtractArchive.py, method: `remove`, a logical expression uses the identity operator. A new object is created inside the identity check operation and then used for matching identity. Since this is a distinct, new object, it will not have identity an match with anything else. As a result, the identity check will have a logical short circuit and the program may have unintended behavior. 
In this case, the following binary operation
queue is []
compares a newly created object with the identity operator which will always evaluate to False.
I suggested that the logical operation should be reviewed for correctness. 
There is a logical short-circuit in the test expression.
Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the …

Update a test expression to fix a logical short circuit

---

src/pyload/plugins/downloaders/TurbobitNet.py

- add new Turbobit Address "tubobeet.net"

[Turbobit] add address www.turbobeet.net

---

src/pyload/plugins/downloaders/TurbobitNet.py

Fixed const "LINK_PREMIUM_PATTERN"
The affected only Premium users:
Turbobit.net falls back to free download for every link, it seems they changed the premium download site.

[Turbobit.com] fixed premium link pattern

---

src/pyload/plugins/downloaders/TurbobitNet.py

Add new base url: 'turbobita.net'

[Turbobit] new base url 'turbobita.net'

---

src/pyload/plugins/downloaders/FastshareCz.py

Make the pattern more generic, as it works on both...
This just extends the respective matching pattern, it seems to work just fine afterwards.
no.

Update FastshareCz.py - also match fastshare.cloud

---

src/pyload/plugins/downloaders/TurbobitNet.py

add torbobit.net to TurbobitNet base pattern
https://torbobit.net was not recognised by TurbobitNet downloader plugin

add torbobit.net to TurbobitNet base pattern

---

src/pyload/webui/app/static/js/captcha-interactive.user.js

https://github.com/pyload/pyload/blob/924d1f243ae813160b6e42f2be1da1e2b18781f1/src/pyload/webui/app/static/js/captcha-interactive.user.js#L106-L106
Directly evaluating user input (for an HTTP request parameter) as code without properly sanitizing the input first allows an attacker arbitrary code execution. This can occur when user input is treated as JavaScript, or passed to a framework which interprets it as an expression to be evaluated. Examples include AngularJS expressions or JQuery selectors.
fix the issue, we should replace the use of `eval()` with a safer alternative. Instead of directly evaluating the code, we can create a controlled sandboxed environment to execute the script securely. One way to do this in modern JavaScript is by using a `Function` constructor, which can limit …

Fix Improper Neutralization of Input code injection interactive.user
