- module/plugins/hooks/ClickAndLoad.py
socket.create_connection doesn't exist in Python 2.5.
But it can be modeled with above function taken from:
https://hg.python.org/cpython/file/2.6/Lib/socket.py#l534
So, it is how 2.6 does it :)
> socket.create_connection is unavailable in Python25

- module/plugins/hooks/JustPremium.py
Justpremium V0.16 [hook for pyload]
Update to V0.16 - 8.8.2014
English
Function:
If you add multiple links and one of it is from a registered premium hoster, all links from non-premium hosters will automatically be removed.
Example:
A DLC with links to uploaded.net, shareonline.biz and zippyfiles.com is added. If you have only an account for uploaded.net, then the two other hosters will be removed.
Options:
unblock this hosters (comma separated): all hosters here (pyloadformat) won't be removed. E.g. use it for your favourite freehoster.
Allow all freehosters and other unknown sites: If this option is activated, only links from hosters available in the pyload "Accounts" list but without account will be removed.
Deutsch
Funktion:
Wenn mehrere Links hinzugefügt werden, und sich darunter …
> [Hook] JustPremium

- module/plugins/hooks/JustPremium.py
This will check if a Multihoster has overwritten some hoster Plugins and will then handle these hosters as premium accounts.
Testet with premiumizeme. Working.
> [JustPremium] Added Multi-Hosters recognition

- module/plugins/hoster/UploadedTo.py
Fixes https://github.com/pyload/pyload/issues/1108
Don't know if it's temporary, but at the moment after Captcha Input there is no more waition time. So Check if download's ready in CheckErrors insert
> Fixed UploadedTo File not downloadable for free users

- module/plugins/hooks/ExtractArchive.py
- module/plugins/internal/Extractor.py
- module/plugins/internal/SevenZip.py
- module/plugins/internal/UnRar.py
- module/plugins/internal/UnZip.py
- repair function only with rar
- added testing option (testing is a litte faster than extracting, so it can be detected if a file is pw protected or has CRC Error a little faster) When testing, extracting is a little faster afterwards (think through caching or something)
- removed periodical run for extract package, because when enabled pyload is always "busy" and therefore my NAS system isn't going to sleep when nothing to do. Furthermore when still extracting when allDownloadsprocessed event is dispatched, double extractions could occur.
- remove deleted packages from extract queue
- event "archive_extracted" moved after check whether extracted files exists, because other hooks could move/delete them before check is done
- deleting rev files and other files created by repairing 
all …
> [ExtractArchive] Some more changes

- module/plugins/hooks/ExtractArchive.py
Noticed when downloading different mirrors, ExtractArchive tries to extract all *.part1 files
Maybe there's a more elegant way to do, but it has to be filtered befor files_ids loop.
> [ExtractArchive] preventing duplicate files extraction

- module/plugins/hoster/ZippyshareCom.py
This version use the internal `Beatifulsoup`. When you'll decide to get rid of it, I suggest to add a dependency on `lxml`.
I've found a way to handle deliberate errors in the JS scripts without relying on `PyV8` by adding JS `try/catch` statements around all the zippyshare scripts.
> Zippyshare bug #1191 correction

- module/plugins/internal/SevenZip.py
- module/plugins/internal/UnRar.py
fixes http://forum.pyload.org/viewtopic.php?f=10&t=4017 and http://forum.pyload.org/viewtopic.php?f=12&t=4032
But not sure if extraction works for them afterwards, because it seems that they have an untested (possible outdated) unrar version installed...
> [ExtractArchive] fixes 'Could not activate UnRar'

- module/plugins/hooks/ExternalScripts.py
Hi,
I don't know if this is the right place to submit patches to pyload, but I would like to submit a small fix:
If a file with unicode characters in the filename is downloaded ExternalScripts.py fails with e.g. this error:
ExternalScripts: Error in download_finished.sh: 'ascii' codec can't decode byte 0xc3 in position 29: ordinal not in range(128)
This commit makes the ExternalScripts plugin encode unicode characters to UTF-8.
> [ExternalScripts] Encode unicode characters

- module/plugins/hooks/ExtractArchive.py
- module/plugins/internal/Extractor.py
- module/plugins/internal/UnRar.py
https://github.com/pyload/pyload/issues/1230
Integrated https://github.com/hsoft/send2trash
With this you don't have to make s2t a dependency for pyload. Maybe you want to do that, but this is just a quick'n'dirty solution.
install using pip: 
pip install send2trash
Tested on windows. Did not effect systems where send2trash isn't installed, except an Errormessage in Log if it isn't installed but selected in config
> [ExtractArchive] Send2Trash Integration

- module/plugins/hoster/ZippyshareCom.py
Zippyshare sometimes encode the file name with an image.
In this case, use the file link to get the file name.
(it's probably a bad hack. I don't know nothing about pyload Core).
> [zippyshare] fix bug #1311

- module/plugins/hooks/ExtractArchive.py
fix #1371 and #1344
This one was nasty.
Apparently extractQueued was called twice by `packageFinished` and `allDownloadsProcessed` causing two threads to try extract and delete the same file which cause things like:
```
11.04.2015 02:21:15 ERROR     ExtractArchive: file01.part40.rar | Archive error | Cannot open file
```
and
```
04.05.2015 22:03:22 DEBUG     ExtractArchive: Successfully moved hg-l10n-201104080000.zip to trash
04.05.2015 22:03:22 INFO      ExtractArchive: hg-l10n-201104080000.zip | Extracting finished
04.05.2015 22:03:22 DEBUG     ExtractArchive: Extracted files: [u'installer/', u'installer]/components/]
04.05.2015 22:03:22 DEBUG     ExtractArchive: setPermissions
self.extract(zipinfo, path, pwd)
File "/usr/lib/python2.7/zipfile.py", line 1028, in extract
return …
```
> [ExtractArchive] [bug] `extractQueued` was called twice

- module/plugins/hooks/ClickAndLoad.py
fix #1387
The solution requires python's SSL lib which  is officially supported in python 2.6+  but there is an installable version for 2.5 (https://pypi.python.org/pypi/ssl/)
> [ClickAndLoad] fix bug when webinterface uses SSL

- pyload/plugin/Container.py
2015-05-10 10:34:17  ERROR     Error importing plugin: [container] DLC (v0.24) | No module named Crypter
File "/opt/pyload/pyload/manager/Plugin.py", line 284, in loadModule
plugins[name]['name'])
File "/opt/pyload/pyload/plugin/container/DLC.py", line 10, in <module>
from pyload.plugin.Container import Container
File "/opt/pyload/pyload/plugin/Container.py", line 10, in <module>
from pyload.plugin.internal.Crypter import Crypter
ImportError: No module named Crypter
2015-05-10 10:34:17  CRITICAL  'NoneType' object has no attribute 'DLC'
File "/opt/pyload/pyload/manager/Thread.py", line 275, in assignJob
job.initPlugin()
File "/opt/pyload/pyload/utils/__init__.py", line 214, in new
return func(*args)
File …
> fixes error on adding container

- module/plugins/hoster/DlFreeFr.py
@vuolter @tmerle 
AdYouLike is currently not used anymore on the hoster's site. Additionally the regex had to be edited to actually grab the domain value. With these changes I could download again until yesterday's update of the plugin.
Seems like this commit isn't actually working: https://github.com/pyload/pyload/commit/6616c00ba1c40f5d56959bd0e4725f26250e1292#diff-5d57a6bc31e3d4fa2d3010afe37c2d46
The original sample link still works for testing:
http://dl.free.fr/b2ANA3gPp
> Remove obsolete AdYouLike call

- module/plugins/crypter/Dereferer.py
- module/plugins/internal/SimpleCrypter.py
```
File "/share/pyload/module/PluginThread.py", line 363, in run
self.active.plugin.preprocessing(self)
File "/share/pyload/module/plugins/Crypter.py", line 49, in preprocessing
self.decrypt(self.pyfile)
File "/etc/pyload/userplugins/internal/SimpleCrypter.py", line 115, in decrypt
self.handleDirect(pyfile)
File "/etc/pyload/userplugins/internal/SimpleCrypter.py", line 104, in handleDirect
header = self.load(self.link or pyfile.url, just_header=True, decode=True)
AttributeError: 'Dereferer' object has no attribute 'link'
```
> [Dereferer] [SimpleCrypter] bugfixes

- module/plugins/crypter/PastedCo.py
- module/plugins/crypter/ShSt.py
I've written 2 new Crypter plugins:
1. sh.st — a URL shortener service much like adf.ly
2. pasted.co — a pastebin website
For testing purposes, here are some URLs:
Random 20MB file hosted on Zippyshare, URL shortened with sh.st: http://sh.st/lExcv
Same file with its URL hosted on pasted.co: http://pasted.co/85f29090
Both services chained (URL on pasted.co, pasted URL shortened with sh.st): http://sh.st/lEb0y
If needed I can also check them vs. the master branch and then create another pull request.
Please note that this is my first pull request on github, so please excuse any major oversights on my part. I'm happy to correct any mistakes I did and I'm grateful for any feedback.
> 2 new Crypter plugins: sh.st and pasted.co

- module/plugins/crypter/ShSt.py
The plugin was broken due to a change of the deadlockers.com website.
The new version of the plugin doesn't rely on third party websites anymore and is also much faster. It uses a special user agent which causes the provider (sh.st) to serve an HTTP redirect instead of a waiting page.
Also, self.urls is now used instead of self.packages for the decrypted URL.
To test the new version, you can use the following URL:
http://sh.st/lExcv
This should lead to you the following download:
http://www39.zippyshare.com/v/6kqYhqFA/file.html
> Update/Fix ShSt crypter plugin

- module/plugins/hoster/GamefrontCom.py
GameFront uses a `<span>` tag around long filenames. This caused the
plugin to include the tag in the filename.
Instead of the (possibly abbreviated) filename in the page's content,
the title (HTML `<title>` tag) is now used.
Use this link to see the issue (file is not really a RAR archive, just a file with random content): http://www.gamefront.com/files/25080153/thisisalongfilenameitssolongicantevenseetheendwowanditsstillgoingonahthereistheend.rar
> Update/Fix GamefrontCom hoster plugin

- module/plugins/hooks/HighWayMeHook.py
- module/plugins/hoster/HighWayMe.py
fix #1532 and rename `hook/HighWayMe.py` to `hook/HighWayMeHook.py`
Should the old `hook/HighWayMe.py` be added to `blacklist.txt`?
> [HighWayMe] Update

- module/plugins/internal/Account.py
the needed premium key is not directly in info, but in the sub-dictionary 'data':
```
{'data': {'login': '******',
'maxtraffic': None,
'options': {'limitdl': ['0']},
'password': '**********',
'premium': True,
'timestamp': 1438159062.570853,
'trafficleft': -1,
'type': 'RealdebridCom',
'valid': True,
'validuntil': 1450976583.0},
'login': {'password': '**********',
'timestamp': 1438159044.071365,
'valid': True}}
```
> Update Account.py, fixed not-working premium downloads

- module/plugins/hoster/PremiumizeMe.py
Current stable is still producing 
```
WARNING	 Download failed: | 'password'
```
because commit 5378494 is missing hoster.
> Fix #1646 (2)

- module/plugins/hooks/AntiStandby.py
```
03.08.2015 01:06:43 ERROR     Error importing AntiStandby: cannot import name fs_join
File "/usr/share/pyload/module/plugins/PluginManager.py", line 268, in loadModule
plugins[name]["name"])
File "/usr/share/pyload/module/plugins/PluginManager.py", line 317, in load_module
module = __import__(newname, globals(), locals(), [plugin])
File "/home/user/.pyload-0.4.9/userplugins/hooks/AntiStandby.py", line 16, in <module>
from module.utils import save_join as fs_encode, fs_join
ImportError: cannot import name fs_join
```
> [AntiStandby] fix import error

- module/plugins/hoster/ZDF.py
The XML file from the ZDF website often contains unicode characters, which lead to errors like
`'ascii' codec can't decode byte 0xc3 in position 29: ordinal not in range(128)`. This change makes the plugin encode unicode characters to UTF-8 before parsing the XML data.
> [ZDF] Encode unicode characters when loading XML

- module/plugins/hoster/ZDF.py
The title used as file name is encoded in Latin-1. This commit enables pyload to download those files and display their names in the queue correctly.
URL to test: http://www.zdf.de/ZDFmediathek/beitrag/video/2455326/Toedliche-Versuchung
> [ZDF] Encode file name / title

- module/plugins/internal/SimpleHoster.py
One some hosters like OneFichier for example, the webpage displays a file size of 1.46GB.
However the real file size can be 1.4649853GB, which makes a difference between the downloaded file size and the expected file size.
size_tolerance is meant for that, but its value is currently set to 1MB. This is an issue in the above case where the difference between expected size and downloaded size is almost 10MB. In many cases, this causes the downloaded file to simply be deleted, even though it has been downloaded without any issue.
The biggest possible size difference is 10MB, at least if the website displays 2 decimals and that the biggest unit is GB. Therefore I propose to change the max tolerance from 1MB to 10MB.
FYI the error message in the log looks like that:
`Fail: File size mismatch | …
> Download deleted because of file size mismatch

- module/plugins/crypter/FilecryptCc.py
- module/plugins/crypter/ShareLinksBiz.py
Fixes the error `'NoneType' object has no attribute 'group'` in the two crypters SharelinksBiz and FilecryptCC which had been reported as #1753.
> [SharelinksBiz & FilecryptCc] Fixes #1753

- module/plugins/accounts/NoPremiumPl.py
- module/plugins/accounts/RapideoPl.py
During the recent changes in the codebase some methods ended with changed signatures. This fixes the problem for Rapideo.pl and NoPremium.pl.
> [Rapideo.pl] [NoPremium.pl] Method signature fix

- module/plugins/hooks/Checksum.py
Replaced all occurences of `computeChecksum()` with `compute_checksum()`. Error was introduced by the recent function name changes without refactoring the source correctly.
Changed the checksum comparison from identity (`is`) to equality (`==`).
> [hooks/Checksum.py] Fix rename error and checksum comparison

- module/plugins/hoster/OneFichierCom.py
```
19.08.2015 00:40:41 ERROR     HOOK UpdateManager: Error updating plugin: [hoster] OneFichierCom.py | Version mismatch
File "/pyload/userplugins/hooks/UpdateManager.py", line 270, in _update_plugins
raise Exception(_("Version mismatch"))
Exception: Version mismatch
```
> [OneFichierCom] fix UpdateManager error: "Version mismatch"

- module/plugins/hoster/YoutubeCom.py
This update resolve the issue raised when you try to share a link from YouTube android app to pyLoad client.
Issue was that the parser doesn't detect youtu.be as a valid URL for YoutubeCom.py and always use BasePlugin.py instead of, that is why the "__pattern__" need to be modified.
The URL_REPLACEMENTS is not appropriate for this short url and was fixed also, in order to construct and typical youtube.com URL, that this script can handle.
> Update to resolve issue #1793

- module/plugins/hoster/OneFichierCom.py
Syntax error in commit [https://github.com/pyload/pyload/commit/10213910fdb5a1c2e7bde50fdd7cdfb99090bf7e] which makes importing OneFichierCom break.
Please test your code before pull requesting.
> Broken OneFIchierCom plugin

- module/plugins/hooks/Checksum.py
The "is" operator checks for object equality, but in this case we want to compare integers.
Reason of change:
02.09.2015 17:32:23	WARNING	HOOK Checksum: File abcdefg.rar has incorrect size: 106954752 B (106954752 expected)
> Checksum.py falsely reports incorrect file size

- module/plugins/hooks/IRCInterface.py
Following Error came up when I tried setting up either IRCInterface or XMPPInterface. 
AttributeError: 'IRCInterface' object has no attribute 'set_daemon'
With my change now it works. Might have been caused by the removal of chamelCase.
> Fix IRCInterface and XMPPInterface

- module/plugins/internal/Plugin.py
```
File "/usr/share/pyload/module/PluginThread.py", line 191, in run
File "/home/user/.pyload-0.4.9/userplugins/internal/Hoster.py", line 184, in preprocessing
File "/home/user/.pyload-0.4.9/userplugins/internal/Hoster.py", line 179, in _process
return self.process(self.pyfile)
File "/home/user/.pyload-0.4.9/userplugins/hoster/MegaCoNz.py", line 218, in process
self.download(mega['g'])
File "/home/user/.pyload-0.4.9/userplugins/internal/Hoster.py", line 404, in download
self.pyfile.name = parse_name(self.pyfile.name)  #: Safe check
File "/home/user/.pyload-0.4.9/userplugins/internal/Plugin.py", line 58, in parse_name
url_p = urlparse.urlparse(url.strip().rstrip('/'))
NameError: …
```
> [Plugin] fix missing import

- module/plugins/internal/Captcha.py
generic fix for #1756:
Requse the hoster http request by default so don't loose the cookies (eg. session cookie)
(Thanks for @ddbxx for spotting this bug)
Useful for `LinkCryptWs` and `FilecryptCC` maybe more
> [Captcha] Requse the hoster http request

- module/plugins/internal/Plugin.py
Strip trailing slashes. Otherwise the last pathname component might be empty
> Strip trailing slashes before case sensitive checking

- module/plugins/internal/XFSHoster.py
after 0c9e92172f69769f72a2a258f717be4bc4d7a397 #1865 is back:
```
File "/usr/share/pyload/module/PluginThread.py", line 191, in run
File "/home/user/.pyload-0.4.9/userplugins/internal/Hoster.py", line 196, in preprocessing
File "/home/user/.pyload-0.4.9/userplugins/internal/Hoster.py", line 191, in _process
return self.process(self.pyfile)
File "/home/user/.pyload-0.4.9/userplugins/internal/SimpleHoster.py", line 279, in process
self.handle_free(pyfile)
File "/home/user/.pyload-0.4.9/userplugins/internal/XFSHoster.py", line 101, in handle_free
data = self.get_post_parameters()
File "/home/user/.pyload-0.4.9/userplugins/internal/XFSHoster.py", line 209, in get_post_parameters …
```
> [XFSHoster] re-fix #1865

- module/plugins/hooks/XFileSharingPro.py
Fixes the regex pattern (masking the `-` in `\w-^_`) that lead to an error `Bad character range`.
> [hooks/XFileSharingPro] Fix for #1954

- module/plugins/internal/Plugin.py
now you can call `self.log_error(_("some error message: %s") % message, traceback=True)` to generate a traceback at will.
also I found that `print_exc()` is not appropriate here because it prints the last exception details but the call to log_xxx() not always is a result of an exception and so, `print_exc()` will print  misleading and false exception information.
> [Plugin] introduce 'traceback' argument in log_xxx() functions

- module/plugins/hooks/UpdateManager.py
following my research in #1991, I discovered a bug thats prevents `UpdateManager` from deleting blacklisted  hook plugins
> [UpdateManager] fix not deleting blacklisted hook plugins

- module/plugins/accounts/UptoboxCom.py
```
13.10.2015 09:57:04 ERROR     HOOK UpdateManager: Error updating plugin: ACCOUNT UptoboxCom | Version mismatch
13.10.2015 09:57:04 ERROR     Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
self.__bootstrap_inner()
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/share/pyload/module/PluginThread.py", line 472, in run
self.f(*self.args, **self.kwargs)
File "/home/user/.pyload-0.4.9/userplugins/hooks/UpdateManager.py", line 152, in update
if self._update() is not 2 or not self.get_config('autorestart'):
File "/home/user/.pyload-0.4.9/userplugins/hooks/UpdateManager.py", line 174, in _update
exitcode = self.update_plugins()
File "/home/user/.pyload-0.4.9/userplugins/hooks/UpdateManager.py", …
```
> [UptoboxCom] fix "Version mismatch"

- module/plugins/internal/Plugin.py
Hi,
I was not happy with the current tracing implementation - it does not print exception information
so I improved tracing:
* Now tracing goes to the log (with `log_exc()` function)
* `log_exc()` will log a `traceback.print_exc()` message with FULL traceback if it detects an exception, otherwise it will log `traceback.print_stack()` message.
* Tracing is off by default (except critical)
* `log_xxx(tracing=True)` will print the traceback regardless of debug mode or not (except `log_debug()`)
Should we print trace only in debug mode? I don`t have a definitive answer for this
> [Plugin] improve error tracing (2)

- module/plugins/hoster/XFileSharingPro.py
```
16.10.2015 14:36:04 WARNING   Download failed: L1f31s5tr4n633p3PSN.part01.rar | 'NoneType' object has no attribute 'PLUGIN_DOMAIN'
File "/usr/share/pyload/module/PluginThread.py", line 191, in run
File "/home/user/.pyload-0.4.9/userplugins/internal/Base.py", line 218, in preprocessing
File "/home/user/.pyload-0.4.9/userplugins/internal/Hoster.py", line 78, in _process
self._setup()
File "/home/user/.pyload-0.4.9/userplugins/hoster/XFileSharingPro.py", line 39, in _setup
account_name     = self.__name__ if self.account.PLUGIN_DOMAIN is None else self.PLUGIN_NAME
AttributeError: 'NoneType' object has no attribute 'PLUGIN_DOMAIN'
```
> [XFileSharingPro] update

- module/plugins/crypter/XFileSharingProFolder.py
```
File "/usr/share/pyload/module/PluginThread.py", line 363, in run
self.active.plugin.preprocessing(self)
File "/usr/share/pyload/module/plugins/internal/Base.py", line 218, in preprocessing
File "/usr/share/pyload/module/plugins/internal/Hoster.py", line 78, in _process
self._setup()
File "/usr/share/pyload/module/plugins/crypter/XFileSharingProFolder.py", line 41, in _setup
account_name     = self.classname if self.account.PLUGIN_DOMAIN is None else self.PLUGIN_NAME
AttributeError: 'NoneType' object has no attribute 'PLUGIN_DOMAIN'
```
> [crypter/XFileSharingProFolder] AttributeError

- module/plugins/hoster/ZDF.py
This ensures that unicode filenames with UTF-8 characters are encoded into ASCII strings, to be compatible to all Pyload methods using `pyfile.name`.
The encoding now is similar to the [YoutubeCom hoster module](https://github.com/pyload/pyload/blob/f61dcaa263750a61f86b4bfbaf9c2cf20c157de0/module/plugins/hoster/YoutubeCom.py#L145).
> [ZDF] Encode file name to ASCII for compatibility

- module/plugins/hoster/BasePlugin.py
This fixes an import of the [Http hoster](https://github.com/pyload/pyload/blob/aff9388d433847fa7adad7421c4d76bd5bdd4e5a/module/plugins/hoster/Http.py), which is not an internal hoster.
I don't know if it is intended to move `Http.py` to the `internal` directory?
> [BasePlugin] Http hoster is not an internal hoster

- module/plugins/internal/Hoster.py
There is a problem that `self.req.code` is not filled if a `BeadHeader` exception occures
This fix will overcome that.
> [Hoster] update

- module/plugins/hooks/ExternalScripts.py
[ExternalScripts.py#L174](https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/ExternalScripts.py#L174) :
`getPackageInfo(pid)` returns a `PackageData` object while all other events gets a `PyPackage` object.
```
20.10.2015 14:30:41 WARNING   Error calling event handler packageDeleted: <bound method ExternalScripts.package_deleted of <Hook ExternalScripts>>, (129,), 'PackageData' object has no attribute 'id'
File "/usr/share/pyload/module/HookManager.py", line 309, in dispatchEvent
f(*args)
File "/home/user/.pyload-0.4.9/userplugins/hooks/ExternalScripts.py", line 181, in package_deleted
args = [pypack.id, pypack.name, dl_folder, pypack.password]
AttributeError: 'PackageData' object has no attribute 'id'
20.10.2015 14:30:43 WARNING   Error …
```
> [ExternalScripts] fix: 'PackageData' object has no attribute 'id'

- module/plugins/hoster/StahnuTo.py
```
24.10.2015 01:07:11 ERROR     Error importing StahnuTo: cannot import name parseFileInfo
File "/usr/share/pyload/module/plugins/PluginManager.py", line 270, in loadModule
plugins[name]["name"])
File "/usr/share/pyload/module/plugins/hoster/StahnuTo.py", line 20, in <module>
from module.plugins.internal.SimpleHoster import SimpleHoster, parseFileInfo
ImportError: cannot import name parseFileInfo
```
> [DeadHoster] StahnuTo

- module/plugins/crypter/YoutubeComFolder.py
line 111 incompatible with python 2.x
```
26.10.2015 00:59:28 ERROR     Error importing YoutubeComFolder: invalid syntax (YoutubeComFolder.py, line 111)
File "/share/pyload/module/plugins/PluginManager.py", line 269, in loadModule
plugins[name]["name"])
File "/share/pyload/module/plugins/PluginManager.py", line 318, in load_module
module = __import__(newname, globals(), locals(), [plugin])
File "/etc/pyload/userplugins/crypter/YoutubeComFolder.py", line 111
relatedplaylist = {p_name: self.get_playlist(p_id) for p_name, p_id in channel['relatedPlaylists'].items()}
^
SyntaxError: invalid syntax
```
> [YoutubeComFolder] update

- module/plugins/hoster/ShareonlineBiz.py
In case of a failure, the regex `r"/failure/(.*?)/1"` in `check_errors` may fail, due to the fact that there can be any other number than 1 following the error message itself, e.g.
`dl/TPDSG2RNU70/failure/freelimit/209715200/363232323337313B666F6F`
> [hoster/ShareonlineBiz] Fix error checking regex

- module/plugins/hoster/DropboxCom.py
Some correction in DropBoxCom.py.
Not sufficient to get it working, but a beginning...
> LINK_PATTERN was missing in DropboxCom.py

- module/plugins/crypter/ShareLinksBiz.py
Previous to the fix, ShareLinksBiz had thrown a `Key error: 'location'` since the request timed out and had not returned the location-field.
Is fixed to fail with 'Could not initialize url' now.
> [ShareLinksBiz] Fix extraction of location url from header

- module/plugins/internal/SimpleHoster.py
Hi,
`http://1fichier.com/?86zu29oou8` is a direct link and is resumable.
Passing `http://1fichier.com/?86zu29oou8` to `isdownload` returns `https://a-9.1fichier.com/s29174186` as a download link, but if you try to download directly from `https://a-9.1fichier.com/s29174186` you get an error.
Also, if a link is a direct link, I don't  see the reason why not use the original link.
> [SimpleHoster] update

- module/plugins/hoster/UpstoreNet.py
- had to introduce the ```self.retry``` on line 86 because Upstore sometimes just restarted the timer on some files without any reason.
- removed artifact config options
- now catches "LONG_WAIT" events
- proper error checking with ```check_errors()```
> various fixes

- module/plugins/hoster/NitroflareCom.py
Alternatively, you could not declare all Hosters to be DIRECT_LINK = True in SimpleHoster.py
> Fix: Nitroflare cannot be handled as Direct Download

- module/plugins/internal/Account.py
- module/plugins/internal/Plugin.py
HI,
After the third time I see someone post a log that reveals his user and password, I think that @joberreiter was right in #2061
To overcome the request logging issue discussed in #2061, this PR will mask the requests of all account plugins.
Now you can reimplement `safe_info`.
> [Plugin] censor ACCOUNT request data

- module/plugins/internal/Container.py
dlc decryption was failing, with error Decrypting failed:****.dlc | global name 'pyfile' is not defined
debug mode showed missing self
>  decryption was failing, with error Decrypting failed:****.dlc | global name 'pyfile' is not defined

- module/plugins/internal/Hoster.py
Python 2.5 does not support `@property.setter`
> [Hoster] Python 2.5 compatibility hack for property.setter

- module/plugins/internal/CaptchaService.py
The file contains a change, that doesn't make it down to us users ;)
pyLoad 0.4.9 Debug Report of ShareonlineBiz 0.65 
```
TRACEBACK:
File "/volume1/web/pyload-git-stable/module/PluginThread.py", line 187, in run
File "/volume1/@optware/share/pyload_config/userplugins/internal/Base.py", line 288, in preprocessing
File "/volume1/@optware/share/pyload_config/userplugins/internal/Hoster.py", line 118, in _process
self.process(self.pyfile)
File "/volume1/@optware/share/pyload_config/userplugins/internal/SimpleHoster.py", line 283, in process
self.handle_free(pyfile)
File "/volume1/@optware/share/pyload_config/userplugins/hoster/ShareonlineBiz.py", line 96, in handle_free
res = …
```
> Bump version of CaptchaService.py

- module/plugins/hooks/ClickNLoad.py
As the title says:
`ClickNLoad` will gracefully close the server socket befor exiting - no more "address already in use" errors (hopefully)
One question:
What is the purpose of the startup delay?
> [ClickNLoad] Shutdown gracefully + code cleanup

- module/plugins/internal/SimpleHoster.py
If someone use "type" method to verify the type of an object on get_info when debugging. They will be a "UnboundLocalError: local variable 'type' referenced before assignment" Error. So I recommend avoiding this name for a temporary variable.
> Avoiding UnboundLocalError when using method 'type' on method get_info from SimpleHoster.

- module/plugins/hoster/ShareonlineBiz.py
Up to now, if a file cannot be downloaded because of "Server is full", it waits 10 minutes a couple of times. And while waiting, nothing else gets downloaded from Shareonline.biz. After a couple of retries, the download will fail anyway. The "server is full" message usually stays for around one day on a file, but it doesn't necessarily affect other files on same hoster.
Proposed solution: Do not wait on "server is full" but fail instead (as mentioned, the failing download will fail anyway). Then, other files on ShareOnline.biz will continue downloading.
> Shareonline.Biz: Fail on full instead of wait

- module/plugins/hoster/OnlineTvRecorder.py
www.onlinetvrecorder.com provides http download links, but returns a http code 503 if you are in a download queue and expects you to retry every 30 seconds to stay in the download queue . So this hoster plugin keeps retrying. Also, only one simultaneously download is allowed.
> Support hoster onlinetvrecorder.com

- module/plugins/internal/UnRar.py
Some tiny error in a regular expression caused unexpected behavior with password
protected archives.
> Regex typo leads to packages not being extracted with Unrar.py

- README
The link: http://pyload.org/ leads to an ads website. Fix to the link provided https://pyload.net/ and the github's wiki links.
> Update broken links in README

- module/plugins/hooks/LinkFilter.py
- LinkFilter
This simple plugin allows to filter all added links.
Example: The filter "random-url.com" will remove all links from queue containing it such as http://random-url.com/fileabc.rar
Multiple filters can be set by seprerating them by comma: "filter1.com,filter2.com"
Example usage: Sort out hosters when a dlc contains multiple hosters.
Future versions: Reverse filter (only allow given filter + option not to filter containers (dlc's))
References: #2519 #182
> Add LinkFilter plugin

- module/plugins/internal/misc.py
If diacritics (Žluťoučký kůň úpěl ďábelské ódy) in filename, pyload return this error:
Maybe this hotfix is best way this time?
Test link: https://uloz.to/!mor9Ans1izOI/zlutoucky-kun-upel-dabelske-ody-txt
`Traceback (most recent call last):
File "/home/ondrej/programming/pyload/module/PluginThread.py", line 187, in run
File "/home/ondrej/programming/pyload/module/plugins/internal/Base.py", line 295, in preprocessing
File "/home/ondrej/programming/pyload/module/plugins/internal/Hoster.py", line 106, in _process
self._setup()
File "/home/ondrej/programming/pyload/module/plugins/internal/Base.py", line 166, in _setup
self.grab_info()
File "/home/ondrej/programming/pyload/module/plugins/internal/Base.py", line 228, in …
> Hotfix UnicodeDecodeError

- module/plugins/hoster/OpenloadIo.py
The hoster openload sometimes requires a captcha to be solved. I followed the api documentation at https://openload.co/api and implemented captcha support for this hoster.
> Add captcha support to the openload hoster plugin

- setup.py
on systems without UTF-8 as default (e.g. in build environments)
> Fix encoding issues when reading README

- module/plugins/hooks/UpdateManager.py
After reconnect I always get an error message, see following log excerpt:
INFO      HOSTER UploadedTo[434]: Checking for link errors...
WARNING   HOSTER UploadedTo[434]: You have reached the max. number of possible free downloads for this hour
DEBUG     HOSTER UploadedTo[434]: WAIT set to timestamp 1495373762.010000 | Previous waitUntil: 0.000000
DEBUG     HOSTER UploadedTo[434]: RECONNECT  required | Previous wantReconnect: False
INFO      HOSTER UploadedTo[434]: Waiting 1 hours...
INFO      HOSTER UploadedTo[434]: Requiring reconnection...
INFO      Starting reconnect
DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
DEBUG     ADDON ExternalScripts: No script found under …
> Bugfix Reconnect Failed: 'ip'

- module/plugins/hooks/DownloadScheduler.py
Currently, DownloadScheduler sets the new `limit_speed` and `max_speed` values. However, a submit from the "Download" config GUI page is required for them to take effect. This change makes DownloadScheduler to automatically submit the new values so they take effect immediately.
> [DownloadScheduler] Make new speed values take effect in pyLoad

- src/pyload/core/config/default.py
Fixed minor typo in `logfile_folder` configuration
> [master] Fix typo in logfile_folder input type

- src/pyload/core/cli.py
`join` expects an iterable, not multiple args, so these were changed to tuples.
Also, changing `sp_stop` to `sp_quit`, as the corresponding function has been renamed.
> [master] Fix join usages in cli file

- src/pyload/core/config/default.py
Added trailing commas to all config sections. This is a bugfix because the `cache_section` variable wasn't a tuple because it had only one element but lacked a trailing comma, so config initialization failed when trying to iterate over it.
Trailing commas are our friends :)
> [master] Fix config default for cache section

- src/pyload/core/iface.py
- src/pyload/core/manager/account.py
- src/pyload/core/manager/addon.py
- src/pyload/core/manager/config.py
- src/pyload/core/manager/event.py
- src/pyload/core/manager/exchange.py
- src/pyload/core/manager/file.py
- src/pyload/core/manager/info.py
- src/pyload/core/manager/plugin.py
- src/pyload/core/manager/remote.py
- src/pyload/core/manager/transfer.py
- src/pyload/core/thread/decrypter.py
> **NOTE:**
Some relative imports are failing because of the `__init__` imports done in some modules, which make inner modules to mess up when trying to import from parent directories. For example:
```
File "~/.virtualenvs/pyload2/bin/pyload", line 11, in <module>
File "~/.virtualenvs/pyload2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 563, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "~/.virtualenvs/pyload2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2651, in load_entry_point
return ep.load()
File …
```
> [master] Change some relative imports to absolute paths

- src/pyload/core/iface.py
CLI `start` command was expecting a `tempdir` parameter, but it was receiving `tmpdir` instead. As the command flag is named `tmpdir`, it was changed to this name, so there's no need to change the CLI
signature.
```
File "build/bdist.linux-x86_64/egg/pyload/core/cli.py", line 156, in main
TypeError: start() got an unexpected keyword argument 'tmpdir'
```
> [master] Fix tmpdir parameter for CLI start command

- src/pyload/core/cli.py
`ico` file is now named `icon.ico`, not `pyload.ico`. See: https://github.com/pyload/pyload/blob/master/media/icon.ico
```
File "build/bdist.linux-x86_64/egg/pyload/core/cli.py", line 148, in main
File "build/bdist.linux-x86_64/egg/pyload/core/cli.py", line 137, in _setup_console
File "$HOME/.virtualenvs/pyload2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1206, in resource_filename
self, resource_name
File "$HOME/.virtualenvs/pyload2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1719, in get_resource_filename
return self._extract_resource(manager, …
```
> [master] Fix Pyload ico path

- src/pyload/core/__init__.py
`pyload.core.plugin` is no longer in this branch, removing to bypass its ImportError.
```
File "$HOME/.virtualenvs/pyload2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 563, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "$HOME/.virtualenvs/pyload2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2651, in load_entry_point
return ep.load()
File "$HOME/.virtualenvs/pyload2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2305, in load
return self.resolve()
File …
```
> [master] Remove import reference to pyload.core.plugin

- src/pyload/core/network/crypter.py
- src/pyload/core/network/hoster.py
`chunks` was completely removed from the `utils` repository (see commit https://github.com/pyload/utils/commit/48da11e8fc8caa391131fdcea12044aecbcc4509), and it seems it's not needed anymore in this code.
```
File "/home/mike/.virtualenvs/pyload2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 563, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "$HOME/.virtualenvs/pyload2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2651, in load_entry_point
return ep.load()
File …
```
> [master] Remove usages of chunks util

- src/pyload/core/init.py
`psp.pid` returns the process ID as an integer number, and it's not a method, so using it as a callable was making it fail.
```
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "build/bdist.linux-x86_64/egg/pyload/core/init.py", line 461, in run
self._init_config()
File "build/bdist.linux-x86_64/egg/pyload/core/init.py", line 328, in _init_config
session = ConfigParser(self.__SESSIONFILENAME, session_defaults)
TypeError: 'int' object is not callable
```
> [master] Fix psp.pid usage

- src/pyload/core/init.py
`RequestFactory` uses the `core` attribute `evm`, which is initialized during `_init_managers`, so we need to do that first.
Relevant log lines:
```
2017-07-26 23:23:28  CRITICAL  'Core' object has no attribute 'evm'
```
> [master] Initialize managers before requests

- src/pyload/core/manager/plugin.py
`PuginLoader` was being incorrectly initialized, as it should be done as the one in the previous line.
Relevant error:
```
CRITICAL  __init__() takes exactly 4 arguments (2 given)
```
> [master] Fix incorrectly initialized PluginLoader

- src/pyload/core/init.py
`AccountManager` does not have a `get_account_infos` method. It seems the correct one to call is `load_accounts` instead.
Relevant error:
```
CRITICAL  'AccountManager' object has no attribute 'get_account_infos'
```
> [master] Rename missing function get_account_infos

- src/pyload/core/init.py
For some reason, this relative import is broken when trying to start pyLoad. By using an absolute import, it gets fixed. Also, moved to the beginning of the file, as it seems there are no circular dependencies.
Relevant error:
```
CRITICAL  find_module() takes exactly 2 arguments (3 given)
```
> [master] Use a global absolute import for RequestFactory

- src/pyload/core/iface.py
This change fixes the `pyload version` CLI command. Because the command functions are treated in a generic way (see https://github.com/pyload/pyload/blob/3323fc51fa2024455728e4a0e85413917641fe0c/src/pyload/core/cli.py#L156), it was failing because of unexpected parameters.
```
File "build/bdist.linux-x86_64/egg/pyload/core/cli.py", line 156, in main
TypeError: version() takes no arguments (6 given)
```
> [master] Fix pyload 'version' command

- src/pyload/core/iface.py
Same fix as https://github.com/pyload/pyload/pull/2923, for the commands `status` and `quit`.
```
File "build/bdist.linux-x86_64/egg/pyload/core/cli.py", line 156, in main
TypeError: status() got an unexpected keyword argument 'restore'
File "build/bdist.linux-x86_64/egg/pyload/core/cli.py", line 156, in main
TypeError: quit() got an unexpected keyword argument 'restore'
```
> [master] Fix CLI commands 'status' and 'quit'

- src/pyload/core/config/default.py
This adds the current folder as the default storage location for pyLoad. It could be changed to a better default value, but we need a default for pyLoad to work, because of the way `availspace` is being used, as it expects a valid path.
Failing line:
https://github.com/pyload/pyload/blob/ac38e1f0ccdb04ae3a697b83954722753a6c5b7c/src/pyload/core/manager/transfer.py#L157
Relevant log error:
```
CRITICAL  [Errno 2] No existe el archivo o el directorio: ''
```
> [master] Add default to storage_folder config option

- src/pyload/core/cli.py
`vars()` returns the internal dict for `args`:
```
(Pdb) print id(args.__dict__)
139935486325936
(Pdb) print id(vars(args))
139935486325936
```
Because of this, the next line doing a `pop` over it actually removes the `command` attribute, which is referenced some lines after it, and it's not found.
```
File "build/bdist.linux-x86_64/egg/pyload/core/cli.py", line 159, in main
AttributeError: 'Namespace' object has no attribute 'command'
```
> [master] Fix inexistent attribute 'command' in CLI execution

- src/pyload/core/init.py
Logging functions only receives a message, and `args` that are interpolated into that message. Current implementation was failing because it was trying to interpolate `str(e)` to a message that doesn't include placeholders for it.
Moved from `.format` to `%`, as that's what `logging` uses for the interpolation.
After the fix:
```
2017-07-26 22:23:58  WARNING   Unable to load `es` language, using default `english`: [Errno 2] No translation file found for domain: u'core'
```
```
File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
msg = self.format(record)
File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
return fmt.format(record)
File "/usr/lib/python2.7/logging/__init__.py", line 465, in format …
```
> [master] Fix logging strings that receive multiple params

- pyload/utils/system.py
> **NOTE:**
Rename exit() to shutdown_os() and fix a bug in this function.
> **NOTE:**
> If this is a **plugin** request, remember to increase the value of the
> `__version__` attribute inside the files you're submitting.
1. **Related pull requests**: _OPTIONAL_
2. **Related issues**: _OPTIONAL_
_OPTIONAL_
_OPTIONAL_
> [master] Rename exit() to shutdown_os()

- pyload/requests/base/request.py
- pyload/requests/curl/request.py
> **NOTE:**
- Rename BAD_HEADERS to BAD_HTTP_RESPONSES and move to pyload.requests.base
- Fix `ResponseException` to include both content and headers attributes (https://github.com/pyload/pyload/pull/2646), **this is very important information for plugins**
- Add `limit` parameter to `CurlRequest` - sometimes the hardcoded 1000000 is not enough.
- Add some unofficial HTTP codes descriptions (https://github.com/pyload/pyload/pull/2600) to `ResponseException `.
> **NOTE:**
> If this is a **plugin** request, remember to increase the value of the
> `__version__` attribute inside the files you're submitting.
1. **Related pull requests**: _OPTIONAL_
2. **Related issues**: _OPTIONAL_
_OPTIONAL_
_OPTIONAL_
> [master] various fixes

- pyload/core/database/backend.py
remove DatabaseBackend object from args as it is added later on anyway (see. [queue](https://github.com/pyload/pyload/blob/master/pyload/core/database/backend.py#L431) and [async](https://github.com/pyload/pyload/blob/master/pyload/core/database/backend.py#L423))
This problem prevents calling DatabaseBackend.commit, DatabaseBackend.rollback and DatabaseBackend.sync_save.
At the moment it seems that commit is only called when pyload exits. If pyload stops working unexpectedly all information will be lost. Maybe commit after every INSERT/UPDATE?
> remove DatabaseBackend object from args

- pyload/core/base.py
the decorator points to the class method. when used during initialisation it points to the method of the object and passes self as argument.
before you might have gotten this error:
Error in atexit._run_exitfuncs:
TypeError: exit() missing 1 required positional argument: 'self'
also removed self.config.close() as ConfigParser does not have a close method
PS: self.exit() at line 277 was unreachable
if exit is not called properly, the database does not commit its changes. Maybe committing changes after inserts of packages etc. should be done within the api, otherwise much information will be lost, if pyload crashes unexpectedly.
> change atexit decorator to method

- module/plugins/crypter/ShareLinksBiz.py
> **NOTE:**
On the webpage the code for the CNL is unified with the code for the DLC files, and the pattern for the DLC extraction changed also alitte bit (addional "m" in get and code afterwards changed also alittle bit)
DLC and CNL extraction isn't working anymore on ShareLinks page. 
This PR provides a fix
> [Plugin ShareLinks.biz] Update 

- pyload/requests/curl/chunk.py
- pyload/requests/curl/download.py
- pyload/requests/curl/request.py
curl/chunk.py rename self.c to self.curl and minor fixes
curl/download.py add implementation for abstract method. removed line self.info.remove as the file has been moved in the previous line
curl/request.py renaming of self.c to self.curl also fix bytes/string problems
needs https://github.com/pyload/pyload/pull/3013 to be merged as well
> rename c -> curl; making abort protected; minor fixes

- module/web/media/js/pyplex/package.js
Fixes `Uncaught SyntaxError: Unexpected identifier` / `Uncaught ReferenceError: PackageUI is not defined` JS errors which prevent Queue tab from working with Pyplex theme
Fix incorrect quotes (`"` instead of `'`) in pyplex/package.js
Fixes `Uncaught SyntaxError: Unexpected identifier` / `Uncaught ReferenceError: PackageUI is not defined` JS errors which prevent Queue tab from working with Pyplex theme
> Fix incorrect quotes in pyplex/package.js

- module/plugins/crypter/FilecryptCc.py
Adding `handle_mirror_pages`/`Handle Mirror Pages` to config.
This way, the user can disable the search for other "mirrors".
Some People create a FilecryptCc link where `?mirror=1` refers to the latest file only and without/or `?mirror=0` to the full package, which will then also download the full package.
> FilecryptCc - optional Mirror handling

- module/plugins/hoster/UptoboxCom.py
> **NOTE:**
For UptoboxCom hoster:
* Using triple double quotes for pattern delimiting
* Allowing values delimiters to be `'` or `"`
* Removing `<` and `>` from `DL_LIMIT_PATTERN`:
* no more found as string is only one line now
* reduced pattern also works with old syntax
If previous fix worked, it is not the case anymore
Previous fix: 70a31b1ac90f4c83655ce6dbbc3ee0021baa8de8
> Patterns improvement + new HTML structure support

- module/plugins/captcha/UlozTo.py
currently  classify_audio_file recognize audio as wav which is wrong type.
_OPTIONAL_
_OPTIONAL_
> [Captcha] Ulozto - fix audio recognition

- module/plugins/hoster/UlozTo.py
> **NOTE:**
set input_type from input url and not as static string
_OPTIONAL_
_OPTIONAL_
> [Hoster] - UlozTo - set input_type from path

- module/plugins/hooks/UpdateManager.py
Changed the SERVER_URL to raw URL of file plugins.txt to avoid http redirect and failing update process (leds to exception)
> [Fix] Correct SERVER_URL to plugins.txt to avoid http redirect

- README.MD
nodejs is supported now.
Also move js2py and node to the beginning as they are way more lightweight than for example rhino (requiring java).
> README: add jsengine node, also prioritize js2py/node

- README.MD
jinja2, beaker and thrift are shipped with pyLoad. Make that clear.
> Shipped libraries don't need to be installed

- module/plugins/hoster/UpstoreNet.py
This fixes the Upstore.net plugin to work for the new recaptcha handling. I just copied the recaptcha part from `internal/XFSHoster.py`. I tested it with a handful of links and it seems to work now.
By the way, it might be nice to be able to avoid this code duplication by importing such `handle_captcha()` from somewhere :)
> use new interactive captcha for Upstore

- src/pyload/webui/app/themes/pyplex/templates/js/packages.js
Webinterface pyplex didn't show the filename of downloaded files.
This will show the filename instead of the files URL.
fixes #3390.
> Package list shows URL instead of filename (#3390)

- module/plugins/hoster/UlozTo.py
Due to using generic one, some hoster url page is wrongly interpreted as "temp. offline".
> [Hoster][Ulozto] Add TEMP_OFFLINE_PATTERN

- module/plugins/hoster/UlozTo.py
Sometimes hoster didn't use captcha to protect direct download link.
> [Hoster] Ulozto - Add non captcha

- module/plugins/accounts/DdlTo.py
Traffic left for ddownload.com may be negative, if the last downloaded file was larger than the traffic left. This will match the negative traffic left instead of falling back to unlimited.
I was also thinking about capping the traffic value to 0 if a negative value is matched, but this has to be done in XFSAccount.py (or by copying the whole grab_info method).. This seems to work as is, as the negative traffic does not match the first pattern in misc.parse_size, which already short circuits to 0.
> fix TRAFFIC_LEFT_PATTERN for ddownload.com not matching negative numbers

- module/plugins/hoster/UptoboxCom.py
Multi Downloads require a premium account, otherwise we start waiting for concurrent downloads but only one really start and others fails.
> [UptoboxCom] multi downloads require premium account

- src/pyload/webui/app/handlers.py
- src/pyload/webui/app/templates/base.html
- src/pyload/webui/app/templates/error.html
The error message before seemed to be a bit buggy, the message "Something went wrong wasn't output, the error message wasn't formated well, just a very long string
The "Something went wrong text is now outputted as subtitle, the errormessage itself is printed in diferent paragrahs, is much more readable
Related to every error message displayed on the ui
Before:
After:
> [Main] Prettier error message in default theme

- src/pyload/webui/app/templates/js/settings.js
The element selector for tiny tab wasn't point to the right one changed tab to top_tab, the settings-page is now working as expected again.
The problem was reported in issue #3728
> [Main] Fix for settingspage in Default theme not working

- src/pyload/webui/app/templates/js/packages.js
I create the link.icon from the linc status as it's also done for the pylex theme (in 4.20 this was done in the python code). Furthermore the call to url_for was replaced by a pure html/js link generation. If the html page is generating the icon name at runtime, so the sever-side (jinia interpreter) can't create the link to the file before the js is running.
The packages in queue and Packages tab are not showing the status icons in the packages details. The browser development console shows a call to the img folder but not a call to a special icon file
> [Main] Fix for missing file status icons in default theme

- src/pyload/webui/app/templates/js/packages.js
Change some missing api endpoint in default theme. Also changed api calls from `this.id` to `this` to make the function calls to `delete_files`, `restart_files` work
The problem only occurs in Default Theme if you try to delete files or restart files in a package. A request to `delete_files/[undefined]` is issued and subsequently the function fails.
-->
> Patch delete files

- src/pyload/plugins/base/downloader.py
- src/pyload/plugins/base/simple_downloader.py
Convert all regexes in scan_download to binary ones, so binary files can be checked
Trying to download a file from anonfiles (e.g. https://anonfiles.com/v5a2adX7oa/Europa-Report.part1_rar) causes the following traceback:
```
[2020-09-20 07:09:12]  DEBUG               pyload  ADDON ExternalScripts: No script found under folder `download_failed`
File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/core/threads/download_thread.py", line 56, in run
File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/plugins/base/hoster.py", line 306, in preprocessing
File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/plugins/base/downloader.py", line 101, in _process …
```
> [Main] Fix scan download cannot use a string pattern on a bytes-like object

- src/pyload/core/__init__.py
- src/pyload/core/api/__init__.py
I converted both problematic calls to a list similar to the path you applied for fixing #3751
Similiar to  #3751 you get the same dictionary changed size during iteration if you press the stop download button while a download is active or if you stop pyload-ng with  a keyboard interrupt (by pressing ctrl+c)
Stopping pyload:
```
[2020-10-10 19:08:08]  INFO                pyload  Download aborted: xxxxx
File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/core/__init__.py", line 331, in start
time.sleep(1)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/__main__.py", line 120, in run
pyload_core.start()
File …
```
> [Main] Fix dictionary changed size during iteration in abort_all_downloads() and stop()

- module/plugins/hoster/RapidgatorNet.py
I fixed free Rapidgator downloads by updating the regular expression to include the https protocol.
Previously, it would keep looping between "Waiting" and asking for a Captcha, now it works again.
Another attempt at #3783, stupid GitHub...
> [RapidgatorNet] Fix accountless downloads

- src/pyload/webui/app/blueprints/json_blueprint.py
Changing package name lead to a traceback. I changed "folder to "_folder" in /edit_package routine
```
[2020-10-24 16:32:36]  DEBUG         pyload.webui  500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/webui/app/blueprints/json_blueprint.py", line 201, in edit_package
api.set_package_data(id, data)
File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/core/api/__init__.py", line 80, in wrapper
return func(self, *args, **kwargs)
File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/core/api/__init__.py", line 987, in set_package_data
setattr(p, key, …
```
>  [Main] Fix rename Package

- src/pyload/core/__init__.py
After starting pyload, go to Settings page -> Permissions and set "Change group of running process" and "Change user of running process" to "on". After a restart of pyload-ng the following traceback is thrown:
```
File "/opt/pyload3/lib/python3.6/site-packages/pyload/core/__init__.py", line 200, in _setup_permissions
os.setgid(group[2])
TypeError: gid should be integer, not str
```
Reason: During refactoring the imports of grp and pwd have been removed, so setid is called with str instead of the right object. This PR fixes this.
> [Main] Fix _setup_permissions - gid should be integer, not str

- src/pyload/plugins/decrypters/DuckCryptInfo.py
- src/pyload/plugins/decrypters/HoerbuchIn.py
- src/pyload/plugins/downloaders/ZippyshareCom.py
This PR moves all HoerbuchIN link pattern to https
Furthermore it solves issues with BeautifulSoup.
1) According to the documentation of BeautifulSoup, `BeautifulStoneSoup` is deprecated:
[https://www.crummy.com/software/BeautifulSoup/bs4/doc/#xml]()
[https://www.crummy.com/software/BeautifulSoup/bs4/doc/#entities]()
2) After removing the convertEntities in both calls of BeautifulSoup the second output arises on stderr. According to documenatation this can be solved by specifiying a parser. 
https://www.crummy.com/software/BeautifulSoup/bs4/doc/#you-need-a-parser
I changed all calls of BeautyfulSoup in all 3 affected plugins:
- HoerbuchIn
- ZippyshareCom
- DuckCryptInfo
1)
```
[2020-10-21 18:21:32]  INFO                pyload  DECRYPTER HoerbuchIn[11]: Processing url: …
```
> [Main] Update hoerbuchIn and Fix BeautyfulSoup

- src/pyload/core/managers/file_manager.py
In https://github.com/pyload/pyload/commit/40243ee5dfbea268dd0cea6f12aaa125e346a342
file_manager was changed to prevent a size changed during iteration bug, this was accidentally reverted during the last merges.
Current version on develop:
> [Main] Fix mismerge file_manager

- src/pyload/webui/app/handlers.py
Currently all calls to an not existing endpoint throw a traceback in the log:
```
[2020-10-25 08:10:23]  DEBUG         pyload.webui  404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.8/dist-packages/flask/helpers.py", line 1083, in send_static_file
return send_from_directory(
File "/usr/local/lib/python3.8/dist-packages/flask/helpers.py", line 767, in send_from_directory …
```
> [Main] Added Errorhandler for Error 404

- src/pyload/__main__.py
- src/pyload/core/__init__.py
If you change the download directory on the web UI and afterwards restart pyload-ng the setting is reset to default. This is caused by the arg parser giving the default storage dir as parameter to the core init function. In the first step the storage dir is saved to the config file. The patch sets the default argument to none and checking in init if some argument is present, if not, the storagedir is loaded from the config file  
Storage dir is not persitant across restarts
> [Main] Fix storagedir not persistent after restart

- src/pyload/core/managers/thread_manager.py
On every reconnect the function first tries to get the ip address from the service http://automation.whatismyip.com, this page is no longer existent, I exchanged it with a working one: icanhazip.com (using this for years now).
Second problem is that get_url returns a binary, so the following regex fails, changing the regex strings to binary ones solves this problem.
On a reconnect the fields for the ip address have been empty before:
```
[2020-10-24 16:46:04]  INFO                pyload  DOWNLOADER DdlTo[1]: Waiting 1 hour, 59 minutes, 57 seconds...
[2020-10-24 16:46:04]  INFO                pyload  DOWNLOADER DdlTo[1]: Requiring reconnection...
[2020-10-24 16:46:04]  INFO                pyload  Starting reconnect
[2020-10-24 16:46:04]  DEBUG               pyload  ADDON ExternalScripts: …
```
> [Main] Fix ip address not resolvable on reconnect

- .travis.yml
Add a Python 3.9 job to our Travis CI test pipeline.
> Add Python 3.9 test on Travis CI

- src/pyload/core/managers/file_manager.py
Changed the parameter of the calls to `get_info_data()` in file_manager.py to the Destination enum to prevent the error below.
Pressing the "delete finished packages", results in error 500:
The follwing traceback is output:
```
[2020-11-01 19:25:52]  DEBUG         pyload.webui  Object of type AttributeError is not JSON serializable
File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/webui/app/blueprints/api_blueprint.py", line 44, in rpc
response = call_api(func, *args, **kwargs)
File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/webui/app/blueprints/api_blueprint.py", line 58, in call_api
result = getattr(api, func)(
File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/core/api/__init__.py", line 80, in wrapper
return func(self, …
```
> [Main] Fix error 500 on delete finished

- src/pyload/plugins/addons/ClickNLoad.py
The click n' load proxy is marked as started, even if it's not started yet. By moving the server_running variable to a point, where the server is really running, the problem can be solved.
If you start pyload-ng and the port the click n' load proxy should listen is already in use. Stopping pyload-ng by keyboard interrupt lasts forever, and pyload-ng isn't stopping quickly.
It's easyly reproducable by having another server listening on port 9666, start pyload-ng, wait for the following message in the log:
```
[2020-11-02 18:21:56]  INFO                pyload  ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
[2020-11-02 18:21:56]  ERROR               pyload  ADDON ClickNLoad: [Errno 98] ...
```
Then try to stop pyload-ng by pressing ctrl+c.
Tested it with python3.8 on Linux Mint running …
> [Main] Fix pyload-ng not stopping if cnl not running

- src/pyload/plugins/decrypters/ChipDe.py
Links from `chip.de` are no longer recognized:
Example: `https://www.chip.de/video/Google-Pixel-5-im-Test-Video_183065048.html`
Moved to https
video links moved to `video-chip` and have `MEDIA` in the link afterwards (in comparsion to the jpg links)
> [Main] Fix Crypter Chip.de

- src/pyload/webui/app/helpers.py
- src/pyload/webui/app/templates/logout.html
- src/pyload/webui/app/themes/modern/templates/logout.html
- src/pyload/webui/app/themes/pyplex/templates/logout.html
On the logout template there is one redirect route, which wasn't considered with the url_for route generating change for making the path_prefix work. This PR addresses this issue. Furthermore I had a problem on login pointing next to the login path, so I excluded this usecase from the next route generation
Problems on logout -> login with path_prefix
> [Main] Add missing url_for on logout -> login redirect

- src/pyload/core/managers/file_manager.py
- src/pyload/core/network/cookie_jar.py
- src/pyload/plugins/base/plugin.py
- src/pyload/plugins/base/simple_downloader.py
- src/pyload/plugins/downloaders/TurbobitNet.py
- src/pyload/plugins/helpers.py
Trying to download a link from turbobit.com, e.g.: https://turbobit.net/bggojpnkq4pt.html
Several changes were needed to make this work:
1) plugin.py the checks for redirect beeing an int is done with isinstance, this also returns true if the class is a derived class, this is the case for int and bool, so I changed it back to type(..) is (chnaged behavior for pyload-ng and pyload, I don't know if this might be intentionally
2) The calls to  set_cookie set the parameter exp with ..timedelta().seconds, this only returns the modulo of minutes/hours/days in seconds, right would be `.total_seconds()`. Currently the cookie expieres instantly, as the timedelta has no left seconds for exactly 31 days timeoffset. This caused turbobit not to accept the cookie as it is expired.
3) In set cookie the …
> [Main] Fix turbobit (cookies, link, redirects)

- src/pyload/plugins/base/simple_downloader.py
After download of a link from ddl pyloadng creates a traceback. Example link: https://ddownload.com/xwp7x8o5ndqw
This is because the downloaded file (binary one is checked against str regex).
I see 2 possibilitys: 
1) Convert self.data on demand to binary .encode('utf-8') and also convert all regexes to binary regexes. A conversion of self.data to str didn't succeed for me as some binary data couldn't converted (see example link)
2) Abort check if self.data is binary, this is what this PR does
```
[2020-10-25 07:07:09]  INFO                pyload  DOWNLOADER DdlTo[11]: Link status: online
[2020-10-25 07:07:09]  INFO                pyload  DOWNLOADER DdlTo[11]: Processing url: https://ddownload.com/xwp7x8o5ndqw
[2020-10-25 07:07:09]  DEBUG               pyload  DOWNLOADER DdlTo[11]: LOAD …
```
> [Main] Fix check errors after download from ddl

- src/pyload/core/managers/thread_manager.py
With https://github.com/pyload/pyload/commit/b4e23f06b84600ab5d186afbc39d5889dd7d9431 get_url now returns a str instead of bytes, so the patch to make the get_ip address work, works no longer, this PR reverts the binary regex and makes it back to a normal "str" regex
Sorry, was my fault not to find the root cause
Get_ip address is again not working
PR:  #3819
> [Main] Revert binary regex on get_ip during reconnect

- src/pyload/core/managers/plugin_manager.py
Currently the regex to find the right plugin is case sensitive, so for example taking the filecrypt decrypter plugin:
`r"https?://(?:www\.)?filecrypt\.cc/Container/\w+"`
This would match: `http://filecrypt.cc/Container/64E039F859.html`
But not: `http://filecrypt.cc/container/64E039F859.html` (C in container not a capital letter)
or: `http://Filecrypt.cc/Container/64E039F859.html` (Capitalized URL)
or even: `HTTP://Filecrypt.cc/Container/64E039F859.html` (Capitalized HTTP)
I added an "ignorecase" flag to the pattern match regex in pluginmanager, this allows us to match all above examples
> [Main] Ignorecase on match plugins

- src/pyload/core/database/user_database.py
There was error at least in `change_password` because of missing salt at beginning
of newpw.
IMHO it is better when `_salted_password` returns password including salt and all
methods are adjusted to it.
I also made little cleanup - isolated salt generation and password checking to
own methods.
> Fix password changing and checking

- src/pyload/core/api/__init__.py
There is a small typo in src/pyload/core/api/__init__.py.
Should read `usable` rather than `usuable`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, usuable -> usable

- module/plugins/internal/Hoster.py
The creation of the download folder was not working, because of missing permissions.
But, this was not mentioned in the log.
The try-except clause was passing the Exception.message property to self.fail(), which was empty in that case, as not all exception subclasses, like OSError, have that defined.
To solve this the exception is passed calling str() before. Thus it just creates a string out of the exception's arguments.
The (premium) download failed, as stated on the log page of pyload, with the following line:
`HOSTER DdlTo[6207]: Premium download failed | downloading`
As you can see, the cause for the failure is not mentioned, as the current status line is printed there ("downloading")
> Premium download failed, not mentioning the real cause

- src/pyload/plugins/accounts/UploadgigCom.py
Uploadgig Account function refers to non existing function "_", correct function name is be "self._". The PR does this change (and also increases version number of the account plugin)
While downloading a file with Uploadgig a traceback is thrown.  
Example Link:
https://uploadgig.com/file/download/896377Cf57E70ecb/rk-dermowen.rar
```
[2021-08-07 08:11:14]  INFO                pyload  Download starts: https://uploadgig.com/file/download/896377Cf57E70ecb/rk-dermowen.rar
[2021-08-07 08:11:14]  DEBUG               pyload  ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
[2021-08-07 08:11:14]  DEBUG               pyload  ADDON UserAgentSwitcher: Setting maximum redirections to 10
[2021-08-07 08:11:14]  DEBUG               pyload  ADDON UserAgentSwitcher: Use custom user-agent …
```
> [Main] Fix traceback in Uploadgig.com account

- src/pyload/plugins/downloaders/NitroflareCom.py
I added hcaptcha to the recognized captcha type for downloader Nitroflare.
Remark: The fallback text captcha wasn't solvable by me (or at least the download didn't work) so I don't know if there is another change in Nitroflare hoster, of if it would be better to remove this option.
At least some (or all?) of the Nitroflare links moved to h-captcha:
The log shows the following while trying to download:
```
[2021-08-07 08:05:55]  INFO                pyload  Download starts: https://nitro.download/view/9CCAA324647A1A4/uiq68cqsf6q5.rar
[2021-08-07 08:05:55]  DEBUG               pyload  ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
[2021-08-07 08:05:55]  DEBUG               pyload  ADDON UserAgentSwitcher: Setting maximum redirections to 10
[2021-08-07 08:05:55]  DEBUG …
```
> [Main] Fix for nitroflare with hcaptcha

- module/plugins/crypter/MultiUpOrg.py
MultiUp.org is now (for couple months already) redirecting all request to https.
It is better to directly use https than depend on redirects, which might bring
more errors.
Just changed addresses from http://www.multiup.org to https://www.multiup.org
Yes, in my case this was required couple months ago (I forgot to send PR) to work. Not sure if it is still needed, maybe redirect is handled correctly now, but it is better in any case to use final address than depend on redirect on their side.
> Use only HTTPS for MultiUp.org

- Dockerfile
Fix pycurl issue when running in docker
The pycurl has confused across 2 different libcurl versions for compilation-time & run-time.
> Fix pycurl issue when running in docker

- module/web/cnl_app.py
Added a method to the click 'n' load plugin that adds the password to a package, if a password was supplied for purposes such as archive extractions etc.
Was trying to add a bunch of archives that are password protected using a click 'n' load button. Although the links and file name was passed through perfectly fine, the password was ignored.
After looking at the `cnl_app.py` file it was clear to see that no method was implemented in dealing with passwords so I added it it.
The click 'n' load data must follow the [JDownloader cnl2 standard](https://jdownloader.org/knowledge/wiki/glossary/cnl2)
> Automatic addition of passwords via Click 'n' Load plugin.

- README.md
- Fix version string
- Added  Click 'N' Load port
- Use local Dockerfile instead of docker hub image (currently not available)
- the current `version` is an integer, which prevents docker-compose from running
- there are no pyload images available on [docker hub](https://hub.docker.com/r/pyload/pyload/tags)
> Improve docker-compose example

- Dockerfile
The latest Jinja2 raises the following error:
AttributeError: module 'jinja2.ext' has no attribute 'autoescape'
This change set Jinja2 to 3.0.3
> Fix #4122, the Docker build error that failed on Jinja2

- module/plugins/internal/SevenZip.py
Will be a solution for #4161 once merged to main.
SevenZip output (16.04 and 21.07) if archive header is encrypted
```bash
Listing archive: /downloads/xxxxx/TW1-5X01.part1.rar
ERROR: /downloads/xxxxx/TW1-5X01.part1.rar : Can not open encrypted archive. Wrong password?
Errors: 1
```
i hope this is a correct way for a fix in pyload-ng, or do i need to create an extra PR?
anyway issue is in 0.4 and 0.5
> SevenZip: fix encrypted header error message

- src/pyload/webui/app/themes/modern/static/css/base.css
- src/pyload/webui/app/themes/pyplex/static/css/base.css
I added the ability to scroll in case the "Add Package" modal is displayed larger than the device's display so that part of the modal reaches outside the screen.
It is not possible to scroll when the modal "Add Package" is displayed on a mobile phone with a smaller display. This causes the "Cancel" and "Add Package" buttons to be off-screen and therefore quite challenging to press.
> "Add Package" modal made scrollable

- src/pyload/plugins/downloaders/UlozTo.py
UlozTo.cz has recently started adding "https" before its captcha URL.
In Pyload, "https:https:" now appears in the captcha URL.
I have removed one of the duplicate HTTPS.
One of the duplicate HTTPS from UlozTo.cz's captcha URL was removed.
Yes. When trying to download from UlozTo.cz I was getting error messages like this
> ...
3491	2022-07-24 10:26:33	DEBUG	pyload	DOWNLOADER UlozTo[34]: LOAD URL https://ulozto.net/reloadXapca.php | get={'rnd': 1658651193505} | post={} | ref=True | cookies=True | just_header=False | decode=True | multipart=False | redirect=True | req=None
3492	2022-07-24 10:26:33	DEBUG	pyload	DOWNLOADER UlozTo[34]: xapca: {"image":"https:https:\/\/xapca.uloz.to\/36aa5f2ef0964e3af3f8669a2d6b79729fe632ef\/image.jpg","sound":"https:https:\/\/xapca.uloz.to\/36aa5f2ef0964e3af3f8 …
> UlozTo.cz duplicate HTTPS in captcha URL

- src/pyload/plugins/addons/HotFolder.py
This PR includes two small changes to the HotFolder plugin:
1. Possibility to filter extensions in the HotFolder. This way one can add (for example) their Downloads directory and only filter out dlc files in there.
2. Add the ability to add packages to the collector and not only the queue
Nope
> Changes to the HotFolder plugin

- Dockerfile
fixes [#4204](https://github.com/pyload/pyload/issues/4204) by using newer `lsiobase/alpine` image with newer Rust version.
[#4204](https://github.com/pyload/pyload/issues/4204)
> fix: Docker build fails building cryptography wheel #4204

- Dockerfile
Some Python dependencies, e.g. cryptography, require newer Rust installed, which is available in newer Alpine.
This change upgrades the Alpine used in Docker container.
Fixes #4204, as a more complete modification replacing #4205.
> Upgrade to Alpine 3.16, fix #4204

- src/pyload/plugins/downloaders/DownsterNet.py
Currently there is a bug in this hoster which prevents extracting packages after download.
This fixes it. The listed file errors anyways doesn't match the response content.
```
File "/home/user/.local/lib/python3.8/site-packages/pyload/core/threads/download_thread.py", line 56, in run
File "/home/user/.local/lib/python3.8/site-packages/pyload/plugins/base/hoster.py", line 291, in preprocessing
File "/home/user/.local/lib/python3.8/site-packages/pyload/plugins/base/multi_downloader.py", line 76, in _process
super()._process(thread)
File "/home/user/.local/lib/python3.8/site-packages/pyload/plugins/base/downloader.py", line 106, in _process
self._check_download()
File …
```
> Fix extracting packages in DownsterNet

- src/pyload/webui/app/themes/modern/templates/base.html
- src/pyload/webui/app/themes/pyplex/templates/base.html
Adds a small workaround to the `modern` and `pyplex` themes to prevent a Flash of Unstyled Content caused by a bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1404468 
As I tested out `pyload-ng` for the first time yesterday, I noticed that on a fresh, local install each page load started out showing unstyled content for about a second before applying the CSS themes. This behavior was already described in an issue a few years ago, which - to my understanding - was closed due to not being deemed important: https://github.com/pyload/pyload/issues/3297
However, for me it notably affected the user experience and the fix is really simple anyway.
> Fix Flash of Unstyled Content in Firefox

- src/pyload/core/__init__.py
Registers a handler for the `SIGTERM` signal that simply calls the `terminate()` function, analogous to the existing `SIGQUIT` handler. 
Using _Docker_ to handle the lifecycle of a _pyload-ng_ container, i.e. with `docker stop pyload-ng` or `docker restart pyload-ng`, resulted in corrupted states where on the next startup _pyload_ could not be started and an error message stating `pyLoad already running with pid 1` was shown.
This is due to _Docker_ using `kill -s SIGTERM 1` to request a graceful shutdown for the process at PID 1 when stopping a container. As this signal is currently not handled by _pyload-ng_, it waits for 10 seconds and then forcefully stops the process, which doesn't correctly remove the `pidfile`.
This problem was mentioned in #3277, but I don't know if it directly …
> Add SIGTERM handler for graceful shutdowns (e.g. when using Docker)

- Dockerfile
Change the way grabbing the Python dependencies when building the Docker image.
The Docker image failed to build in the latest commit, after `;python_version=='3.6'` etc. markers added.
> A cleaner way to build wheels

- src/pyload/plugins/downloaders/FiregetCom.py
updated url pattern in FiregetCom downloader
fireget.com supports https, the plugin did not assign urls starting in https to the FiregetCom downloader.
This PR fixes that.
Replaces https://github.com/pyload/pyload/pull/4298
> [FiregetCom] support https urls

- src/pyload/plugins/accounts/UploadgigCom.py
The uploadgig plugin was attempting to call a `CookieJar` method named `parseCookie`, rather than `parse_cookie`.
Attempting to start pyload with an uploadgig account would result in an `AttributeError` exception and pyload would be unable to start.
> [UploadgigCom] Fix call to parse_cookie method

- src/pyload/core/utils/web/parse.py
- tests/test_parse.py
This changes the `name` function to allow for `#` in filenames, such as `graph #1 of 2.png`. There aren't any tests around what this function was supposed to be doing though, so this may need some more tweaking to make it consistently useful.
Fixes #4351
> Support '#' in filenames

- setup.cfg
Seems that a new cryptography release [disabled support for certain versions of cryptography on pypi](https://github.com/pyload/pyload/actions/runs/5805223514/job/15736016133?pr=4350). this should fix it
```
Collecting cryptography>=35.0.0
Downloading cryptography-41.0.3.tar.gz (630 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 630.1/630.1 kB 49.9 MB/s eta 0:00:00
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'error'
... snipped ... 
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [15 lines of output]
File "/home/runner/work/pyload/pyload/.tox/pypy/site-packages/pip/_vend …
```
> Don't install new versions of cryptography on pypy

- src/pyload/plugins/accounts/UlozTo.py
The `INFO_PATTERN` for UlozTo account is not longer working, therefore I introduced a new one that works.
I added my UlozTo account with active data plan, but in "Accounts" section was written that the plugin was not able to obtain information about my account and the PyLoad was using for my downloads free links.
No additional references.
> [UlozTo] Fix account info pattern

- src/pyload/plugins/extractors/UnRar.py
This adds a new (default off) option which if enabled passes `-ai` to `unrar`, which ignores file attributes stored in RAR archives.
This should help with cases where file permissions are set to odd values that may result in users not being able to modify extracted files. By ignoring attributes, permissions are handled by the underlying OS functions of creating a file.
I run pyload-ng on a NAS where file and directory permissions are set up using ACLs. When unpacking RAR archives I was greeted with permission errors when trying to move or rename files that were inside nested directories in the RAR archive. Some of the files also had odd permissions set by default. This should™ alleviate this issue entirely. And if not... well, I'm sure it'll help *someone*.
The same issue was discussed 9 …
> [UnRar] Allow extraction ignoring file attributes

- src/pyload/plugins/accounts/ArchiveOrg.py
This fixes the login check for archive.org.
Despite adding an account for archive.org I got `401 Unauthorized` when I tried to download a file, that requires an account. This is because the login check failed and pyload skipped the login.
> ArchiveOrg: Fix login check

- src/pyload/webui/app/themes/modern/templates/js/settings.js
- src/pyload/webui/app/themes/pyplex/templates/js/settings.js
Use `String.prototype.includes()` instead of `String.prototype.startsWith()` for the search of plugins in the settings.
Currently, the search only matches the beginning of a plugin. This is not very helpful if the full name of a plugin is not known. For example, a search for "9kw" would not find the plugin "Captcha9kw". Due to the large amount if plugins it is also difficult to find plugins by simply scrolling through.
This PR changes the search so it checks whether the search string is not only matched to the beginning of a plugins name but if the string a somewhere contained.
Unfortunately, this change has also some drawbacks: e.g. filtering plugin names by starting letter. But, currently, the plugins are sorted alphabetically, therefore this type of search can be done by looking at the …
> Make search for plugins in settings more fuzzy

- src/pyload/webui/app/themes/modern/templates/base.html
- src/pyload/webui/app/themes/pyplex/templates/base.html
- src/pyload/webui/app/themes/pyplex/templates/captcha.html
Fix some minor HTML markup errors in the "modern" and "pyplex" theme template files, like missing closing quotation marks, superfluous tags and empty attributes.
No.
The markup could be improved further, e. g. via HTML validation tools like [W3C Validator](https://validator.w3.org).
> Fix some HTML markup errors in template files
